// Danh mục công việc chính thức CBQL - GV - NV thực hiện giai đoạn Tháng 6/2026 đến Tháng 9/2026
export interface JobItem {
  id: string;
  role: 'CBQL' | 'GV' | 'NV';
  roleName: string;
  tt: number;
  name: string;
  spcvFull: string;
  spcvCode: string;
  spcvName: string;
  deadline: string;
  targetQuantity: number;
  targetQuality: number;
  targetProgress: number;
  notes: string;
}

export const JOBS_DATA: {
  cbql: JobItem[];
  gv: JobItem[];
  nv: JobItem[];
} = {
  "cbql": [
    {
      "id": "CBQL_1",
      "role": "CBQL",
      "roleName": "Cán bộ Quản lý (BGH)",
      "tt": 1,
      "name": "Tổng hợp kết quả đánh giá, xếp loại chất lượng viên chức, người lao động cuối năm học 2025 - 2026 theo Nghị định 90/2020 & 48/2023",
      "spcvFull": "N2_1046 - Tham mưu công tác đánh giá, xếp loại",
      "spcvCode": "N2_1046",
      "spcvName": "Tham mưu công tác đánh giá, xếp loại",
      "deadline": "10/06/2026",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Biên bản họp Hội đồng đánh giá xếp loại viên chức năm học 2025-2026"
    },
    {
      "id": "CBQL_2",
      "role": "CBQL",
      "roleName": "Cán bộ Quản lý (BGH)",
      "tt": 2,
      "name": "Ban hành Quyết định công nhận kết quả đánh giá, xếp loại viên chức, người lao động và công khai toàn trường",
      "spcvFull": "N2_1046 - Tham mưu công tác đánh giá, xếp loại",
      "spcvCode": "N2_1046",
      "spcvName": "Tham mưu công tác đánh giá, xếp loại",
      "deadline": "18/06/2026",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Quyết định số 85/QĐ-THPT công nhận kết quả xếp loại"
    },
    {
      "id": "CBQL_3",
      "role": "CBQL",
      "roleName": "Cán bộ Quản lý (BGH)",
      "tt": 1,
      "name": "Chỉ đạo thẩm định hồ sơ thi đua, sáng kiến kinh nghiệm của CBGVNV đề nghị công nhận LĐTT, CSTĐ cơ sở năm học 2025 - 2026",
      "spcvFull": "N1_576 - Tiếp nhận, thẩm định hồ sơ đề nghị xét tặng thưởng danh hiệu Lao động tiên tiến, Chiến sỹ thi đua cơ sở và hồ sơ trình khen thưở",
      "spcvCode": "N1_576",
      "spcvName": "Tiếp nhận, thẩm định hồ sơ đề nghị xét tặng thưởng danh hiệu Lao động tiên tiến, Chiến sỹ thi đua cơ sở và hồ sơ trình khen thưở",
      "deadline": "15/06/2026",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Biên bản thẩm định hồ sơ sáng kiến kinh nghiệm và thi đua"
    },
    {
      "id": "CBQL_4",
      "role": "CBQL",
      "roleName": "Cán bộ Quản lý (BGH)",
      "tt": 2,
      "name": "Tổ chức họp Hội đồng Thi đua - Khen thưởng nhà trường xét duyệt danh hiệu và hoàn thiện tờ trình nộp Sở GD&ĐT",
      "spcvFull": "N1_576 - Tiếp nhận, thẩm định hồ sơ đề nghị xét tặng thưởng danh hiệu Lao động tiên tiến, Chiến sỹ thi đua cơ sở và hồ sơ trình khen thưở",
      "spcvCode": "N1_576",
      "spcvName": "Tiếp nhận, thẩm định hồ sơ đề nghị xét tặng thưởng danh hiệu Lao động tiên tiến, Chiến sỹ thi đua cơ sở và hồ sơ trình khen thưở",
      "deadline": "22/06/2026",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Tờ trình số 28/TTr-THPT đề nghị khen thưởng năm học 2025-2026"
    },
    {
      "id": "CBQL_5",
      "role": "CBQL",
      "roleName": "Cán bộ Quản lý (BGH)",
      "tt": 1,
      "name": "Rà soát, chuẩn bị đầy đủ phòng thi, camera giám sát, thiết bị PCCC, phòng bảo quản đề thi, bài thi phục vụ Điểm thi tốt nghiệp THPT năm 2026",
      "spcvFull": "N1_580 - Phối hợp chuẩn bị các điều kiện về cơ sở vật chất, trang thiết bị phục vụ cho công tác tổ chức kỳ thi tuyển sinh 10; thi tốt ngh",
      "spcvCode": "N1_580",
      "spcvName": "Phối hợp chuẩn bị các điều kiện về cơ sở vật chất, trang thiết bị phục vụ cho công tác tổ chức kỳ thi tuyển sinh 10; thi tốt ngh",
      "deadline": "20/06/2026",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Biên bản kiểm tra điều kiện CSVC Điểm thi tốt nghiệp THPT năm 2026"
    },
    {
      "id": "CBQL_6",
      "role": "CBQL",
      "roleName": "Cán bộ Quản lý (BGH)",
      "tt": 2,
      "name": "Phối hợp với chính quyền địa phương, công an, y tế bảo đảm an ninh trật tự, an toàn giao thông và phòng chống dịch bệnh kỳ thi tốt nghiệp",
      "spcvFull": "N1_580 - Phối hợp chuẩn bị các điều kiện về cơ sở vật chất, trang thiết bị phục vụ cho công tác tổ chức kỳ thi tuyển sinh 10; thi tốt ngh",
      "spcvCode": "N1_580",
      "spcvName": "Phối hợp chuẩn bị các điều kiện về cơ sở vật chất, trang thiết bị phục vụ cho công tác tổ chức kỳ thi tuyển sinh 10; thi tốt ngh",
      "deadline": "25/06/2026",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Kế hoạch phối hợp liên ngành bảo đảm an ninh trật tự kỳ thi"
    },
    {
      "id": "CBQL_7",
      "role": "CBQL",
      "roleName": "Cán bộ Quản lý (BGH)",
      "tt": 1,
      "name": "Thành lập Hội đồng tuyển sinh lớp 10 THPT năm học 2026 - 2027; ban hành Thông báo hướng dẫn tuyển sinh",
      "spcvFull": "N2_1097 - Hướng dẫn tuyển sinh lớp 10 trung học phổ thông năm học 2026 - 2027",
      "spcvCode": "N2_1097",
      "spcvName": "Hướng dẫn tuyển sinh lớp 10 trung học phổ thông năm học 2026",
      "deadline": "15/06/2026",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Quyết định thành lập HĐTS và Thông báo số 12/TB-THPT tuyển sinh lớp 10"
    },
    {
      "id": "CBQL_8",
      "role": "CBQL",
      "roleName": "Cán bộ Quản lý (BGH)",
      "tt": 2,
      "name": "Chỉ đạo thu nhận hồ sơ, xét tuyển, hoàn thành duyệt danh sách trúng tuyển lớp 10 trình Sở GD&ĐT phê duyệt",
      "spcvFull": "N2_1097 - Hướng dẫn tuyển sinh lớp 10 trung học phổ thông năm học 2026 - 2027",
      "spcvCode": "N2_1097",
      "spcvName": "Hướng dẫn tuyển sinh lớp 10 trung học phổ thông năm học 2026",
      "deadline": "25/07/2026",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Danh sách học sinh trúng tuyển lớp 10 đã được Sở GD&ĐT phê duyệt"
    },
    {
      "id": "CBQL_9",
      "role": "CBQL",
      "roleName": "Cán bộ Quản lý (BGH)",
      "tt": 1,
      "name": "Xây dựng Kế hoạch bồi dưỡng chính trị hè năm 2026 và bồi dưỡng chuyên môn nghiệp vụ cho cán bộ quản lý, giáo viên",
      "spcvFull": "N3_652 - Xây dựng Kế hoạch đào tạo, bồi dưỡng công chức, viên chức",
      "spcvCode": "N3_652",
      "spcvName": "Xây dựng Kế hoạch đào tạo, bồi dưỡng công chức, viên chức",
      "deadline": "10/07/2026",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Kế hoạch số 45/KH-THPT bồi dưỡng chính trị và chuyên môn hè 2026"
    },
    {
      "id": "CBQL_10",
      "role": "CBQL",
      "roleName": "Cán bộ Quản lý (BGH)",
      "tt": 1,
      "name": "Chỉ đạo rà soát, xét duyệt quyết toán thu chi ngân sách 6 tháng đầu năm 2026 và đối chiếu kho bạc",
      "spcvFull": "N2_1158 - Xét duyệt quyết toán ngân sách Nhà nước hàng năm",
      "spcvCode": "N2_1158",
      "spcvName": "Xét duyệt quyết toán ngân sách Nhà nước hàng năm",
      "deadline": "15/07/2026",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Báo cáo quyết toán tài chính ngân sách 6 tháng đầu năm 2026"
    },
    {
      "id": "CBQL_11",
      "role": "CBQL",
      "roleName": "Cán bộ Quản lý (BGH)",
      "tt": 2,
      "name": "Cử cán bộ quản lý, giáo viên tham gia đầy đủ các lớp tập huấn SGK, phương pháp giảng dạy và ứng dụng AI do Sở GD&ĐT tổ chức",
      "spcvFull": "N3_652 - Xây dựng Kế hoạch đào tạo, bồi dưỡng công chức, viên chức",
      "spcvCode": "N3_652",
      "spcvName": "Xây dựng Kế hoạch đào tạo, bồi dưỡng công chức, viên chức",
      "deadline": "15/08/2026",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Quyết định cử cán bộ, giáo viên dự tập huấn hè năm 2026"
    },
    {
      "id": "CBQL_12",
      "role": "CBQL",
      "roleName": "Cán bộ Quản lý (BGH)",
      "tt": 1,
      "name": "Kiểm tra, nghiệm thu công tác sửa chữa phòng học, bàn ghế, hệ thống điện nước, mái che và vệ sinh khuôn viên trường trong hè",
      "spcvFull": "N3_684 - Tham mưu triển khai công tác thuộc lĩnh vực Cơ sở vật chất",
      "spcvCode": "N3_684",
      "spcvName": "Tham mưu triển khai công tác thuộc lĩnh vực Cơ sở vật chất",
      "deadline": "15/08/2026",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Biên bản nghiệm thu tu sửa cơ sở vật chất hè 2026"
    },
    {
      "id": "CBQL_13",
      "role": "CBQL",
      "roleName": "Cán bộ Quản lý (BGH)",
      "tt": 2,
      "name": "Rà soát, mua sắm bổ sung thiết bị dạy học tối thiểu, sách thư viện và hóa chất thí nghiệm chuẩn bị năm học mới 2026 - 2027",
      "spcvFull": "N3_684 - Tham mưu triển khai công tác thuộc lĩnh vực Cơ sở vật chất",
      "spcvCode": "N3_684",
      "spcvName": "Tham mưu triển khai công tác thuộc lĩnh vực Cơ sở vật chất",
      "deadline": "25/08/2026",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Hợp đồng mua sắm thiết bị dạy học và sách thư viện"
    },
    {
      "id": "CBQL_14",
      "role": "CBQL",
      "roleName": "Cán bộ Quản lý (BGH)",
      "tt": 1,
      "name": "Ban hành Quyết định phân công nhiệm vụ cán bộ quản lý, phân công chuyên môn giáo viên và biên chế học sinh các lớp năm học 2026 - 2027",
      "spcvFull": "N1_585 - Chỉ đạo việc thực hiện các nhiệm vụ đầu năm học 2026 - 2027",
      "spcvCode": "N1_585",
      "spcvName": "Chỉ đạo việc thực hiện các nhiệm vụ đầu năm học 2026",
      "deadline": "20/08/2026",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Quyết định số 102/QĐ-THPT về phân công nhiệm vụ năm học 2026-2027"
    },
    {
      "id": "CBQL_15",
      "role": "CBQL",
      "roleName": "Cán bộ Quản lý (BGH)",
      "tt": 2,
      "name": "Chỉ đạo tổ chức ngày tựu trường, đón học sinh lớp 10 và tổ chức tuần sinh hoạt tập thể đầu năm học 2026 - 2027",
      "spcvFull": "N1_585 - Chỉ đạo việc thực hiện các nhiệm vụ đầu năm học 2026 - 2027",
      "spcvCode": "N1_585",
      "spcvName": "Chỉ đạo việc thực hiện các nhiệm vụ đầu năm học 2026",
      "deadline": "28/08/2026",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Kế hoạch tựu trường và tuần sinh hoạt tập thể học sinh đầu năm"
    },
    {
      "id": "CBQL_16",
      "role": "CBQL",
      "roleName": "Cán bộ Quản lý (BGH)",
      "tt": 1,
      "name": "Xây dựng Kế hoạch và chỉ đạo tổ chức Lễ Khai giảng năm học mới 2026 - 2027 trang trọng, ý nghĩa, an toàn và tiết kiệm",
      "spcvFull": "N3_666 - Kế hoạch tham dự Lễ Khai giảng năm học 2026 - 2027 tại các cơ sở giáo dục trên địa bàn tỉnh Cao Bằng",
      "spcvCode": "N3_666",
      "spcvName": "Kế hoạch tham dự Lễ Khai giảng năm học 2026",
      "deadline": "05/09/2026",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Kế hoạch tổ chức Lễ Khai giảng năm học 2026-2027"
    },
    {
      "id": "CBQL_17",
      "role": "CBQL",
      "roleName": "Cán bộ Quản lý (BGH)",
      "tt": 1,
      "name": "Xây dựng và ban hành Kế hoạch giáo dục nhà trường, kế hoạch thực hiện nhiệm vụ trọng tâm năm học 2026 - 2027",
      "spcvFull": "N3_668 - Quyết định ban hành Kế hoạch nhiệm vụ, giải pháp trọng tâm năm học 2026 - 2027 của ngành Giáo dục tỉnh Cao Bằng",
      "spcvCode": "N3_668",
      "spcvName": "Quyết định ban hành Kế hoạch nhiệm vụ, giải pháp trọng tâm năm học 2026",
      "deadline": "10/09/2026",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Kế hoạch giáo dục nhà trường năm học 2026-2027"
    },
    {
      "id": "CBQL_18",
      "role": "CBQL",
      "roleName": "Cán bộ Quản lý (BGH)",
      "tt": 2,
      "name": "Phê duyệt kế hoạch giáo dục của các tổ chuyên môn, tổ văn phòng và các bộ phận trong nhà trường năm học 2026 - 2027",
      "spcvFull": "N3_668 - Quyết định ban hành Kế hoạch nhiệm vụ, giải pháp trọng tâm năm học 2026 - 2027 của ngành Giáo dục tỉnh Cao Bằng",
      "spcvCode": "N3_668",
      "spcvName": "Quyết định ban hành Kế hoạch nhiệm vụ, giải pháp trọng tâm năm học 2026",
      "deadline": "18/09/2026",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Kế hoạch năm học các tổ TN, XH, VP đã phê duyệt"
    },
    {
      "id": "CBQL_19",
      "role": "CBQL",
      "roleName": "Cán bộ Quản lý (BGH)",
      "tt": 3,
      "name": "Chỉ đạo tổ chức thành công Hội nghị cán bộ, viên chức, người lao động năm học 2026 - 2027",
      "spcvFull": "N3_668 - Quyết định ban hành Kế hoạch nhiệm vụ, giải pháp trọng tâm năm học 2026 - 2027 của ngành Giáo dục tỉnh Cao Bằng",
      "spcvCode": "N3_668",
      "spcvName": "Quyết định ban hành Kế hoạch nhiệm vụ, giải pháp trọng tâm năm học 2026",
      "deadline": "28/09/2026",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Nghị quyết Hội nghị CBVC-NLĐ năm học 2026-2027"
    },
    {
      "id": "CBQL_20",
      "role": "CBQL",
      "roleName": "Cán bộ Quản lý (BGH)",
      "tt": 1,
      "name": "Xây dựng lịch công tác tuần, tháng 9 và chương trình điều hành tổng thể hoạt động sư phạm toàn trường",
      "spcvFull": "N1_610 - Chủ trì xây dựng kế hoạch, chương trình công tác của Phòng",
      "spcvCode": "N1_610",
      "spcvName": "Chủ trì xây dựng kế hoạch, chương trình công tác của Phòng",
      "deadline": "05/09/2026",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Lịch công tác tuần tháng 9/2026 đăng tải trên cổng thông tin điện tử"
    },
    {
      "id": "CBQL_21",
      "role": "CBQL",
      "roleName": "Cán bộ Quản lý (BGH)",
      "tt": 1,
      "name": "Tổ chức họp giao ban BGH và họp Hội đồng sư phạm tháng 9/2026 đánh giá triển khai nhiệm vụ năm học mới",
      "spcvFull": "N1_611 - Tổ chức, điều hành, đánh giá kết quả thực hiện nhiệm vụ của công chức thuộc phòng",
      "spcvCode": "N1_611",
      "spcvName": "Tổ chức, điều hành, đánh giá kết quả thực hiện nhiệm vụ của công chức thuộc phòng",
      "deadline": "15/09/2026",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Biên bản họp Hội đồng sư phạm tháng 9/2026"
    },
    {
      "id": "CBQL_22",
      "role": "CBQL",
      "roleName": "Cán bộ Quản lý (BGH)",
      "tt": 2,
      "name": "Kiểm tra, đôn đốc tiến độ thực hiện chương trình giảng dạy và nền nếp chuyên môn tháng 9",
      "spcvFull": "N1_611 - Tổ chức, điều hành, đánh giá kết quả thực hiện nhiệm vụ của công chức thuộc phòng",
      "spcvCode": "N1_611",
      "spcvName": "Tổ chức, điều hành, đánh giá kết quả thực hiện nhiệm vụ của công chức thuộc phòng",
      "deadline": "30/09/2026",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Báo cáo kiểm tra nền nếp dạy học tháng 9/2026"
    },
    {
      "id": "CBQL_23",
      "role": "CBQL",
      "roleName": "Cán bộ Quản lý (BGH)",
      "tt": 1,
      "name": "Tổng hợp số liệu đầu năm, kiểm tra việc ổn định nền nếp dạy học tháng 9 và báo cáo Sở GD&ĐT đúng thời hạn",
      "spcvFull": "N2_1131 - Tổng hợp báo cáo tình hình triển khai nhiệm vụ đầu năm học 2026 - 2027",
      "spcvCode": "N2_1131",
      "spcvName": "Tổng hợp báo cáo tình hình triển khai nhiệm vụ đầu năm học 2026",
      "deadline": "20/09/2026",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Báo cáo tình hình triển khai nhiệm vụ đầu năm học gửi Sở GD&ĐT"
    },
    {
      "id": "CBQL_24",
      "role": "CBQL",
      "roleName": "Cán bộ Quản lý (BGH)",
      "tt": 2,
      "name": "Chỉ đạo triển khai công tác tuyên truyền phổ biến pháp luật, an toàn giao thông và cam kết an ninh trật tự trường học tháng 9",
      "spcvFull": "N2_1131 - Tổng hợp báo cáo tình hình triển khai nhiệm vụ đầu năm học 2026 - 2027",
      "spcvCode": "N2_1131",
      "spcvName": "Tổng hợp báo cáo tình hình triển khai nhiệm vụ đầu năm học 2026",
      "deadline": "25/09/2026",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Bản cam kết an toàn giao thông và phòng chống bạo lực học đường"
    },
    {
      "id": "CBQL_25",
      "role": "CBQL",
      "roleName": "Cán bộ Quản lý (BGH)",
      "tt": 1,
      "name": "Ban hành Thông báo Lịch tiếp công dân năm học 2026 - 2027; tiếp nhận và giải quyết kịp thời phản ánh của phụ huynh đầu năm học",
      "spcvFull": "N1_572 - Tiếp công dân định kỳ cùng Giám đốc Sở GDĐT",
      "spcvCode": "N1_572",
      "spcvName": "Tiếp công dân định kỳ cùng Giám đốc Sở GDĐT",
      "deadline": "15/09/2026",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Thông báo lịch tiếp công dân năm học 2026-2027 và sổ tiếp dân"
    }
  ],
  "gv": [
    {
      "id": "GV_1",
      "role": "GV",
      "roleName": "Giáo viên (Bộ môn / Chủ nhiệm / Tổ trưởng)",
      "tt": 1,
      "name": "Hoàn thành chấm bài, vào điểm, tổng kết đánh giá xếp loại học sinh cuối năm học 2025 - 2026 trên phần mềm VnEdu",
      "spcvFull": "N1_564 - Quản lý dữ liệu của các Kỳ thi",
      "spcvCode": "N1_564",
      "spcvName": "Quản lý dữ liệu của các Kỳ thi",
      "deadline": "05/06/2026",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Sổ điểm điện tử năm học 2025-2026 trên hệ thống VnEdu"
    },
    {
      "id": "GV_2",
      "role": "GV",
      "roleName": "Giáo viên (Bộ môn / Chủ nhiệm / Tổ trưởng)",
      "tt": 2,
      "name": "Thực hiện nhiệm vụ coi thi, chấm thi kỳ thi tuyển sinh lớp 10 THPT và kỳ thi tốt nghiệp THPT năm 2026 theo điều động của Sở",
      "spcvFull": "N1_564 - Quản lý dữ liệu của các Kỳ thi",
      "spcvCode": "N1_564",
      "spcvName": "Quản lý dữ liệu của các Kỳ thi",
      "deadline": "30/06/2026",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Quyết định điều động cán bộ coi thi, chấm thi của Sở GD&ĐT"
    },
    {
      "id": "GV_3",
      "role": "GV",
      "roleName": "Giáo viên (Bộ môn / Chủ nhiệm / Tổ trưởng)",
      "tt": 1,
      "name": "Hoàn thiện hồ sơ sáng kiến kinh nghiệm, hồ sơ minh chứng đề nghị đánh giá xếp loại viên chức cuối năm học 2025 - 2026",
      "spcvFull": "N3_658 - Thẩm định hồ sơ và tham mưu công tác sáng kiến, đề tài nghiên cứu khoa học; các cuộc thi về công tác học sinh sinh viên; hồ sơ b",
      "spcvCode": "N3_658",
      "spcvName": "Thẩm định hồ sơ và tham mưu công tác sáng kiến, đề tài nghiên cứu khoa học; các cuộc thi về công tác học sinh sinh viên; hồ sơ b",
      "deadline": "10/06/2026",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Báo cáo sáng kiến kinh nghiệm và phiếu tự đánh giá viên chức"
    },
    {
      "id": "GV_4",
      "role": "GV",
      "roleName": "Giáo viên (Bộ môn / Chủ nhiệm / Tổ trưởng)",
      "tt": 1,
      "name": "Tham gia đầy đủ lớp bồi dưỡng chính trị hè năm 2026 và hoàn thành bài thu hoạch đạt yêu cầu",
      "spcvFull": "N3_652 - Xây dựng Kế hoạch đào tạo, bồi dưỡng công chức, viên chức",
      "spcvCode": "N3_652",
      "spcvName": "Xây dựng Kế hoạch đào tạo, bồi dưỡng công chức, viên chức",
      "deadline": "25/07/2026",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Bài thu hoạch bồi dưỡng chính trị hè 2026"
    },
    {
      "id": "GV_5",
      "role": "GV",
      "roleName": "Giáo viên (Bộ môn / Chủ nhiệm / Tổ trưởng)",
      "tt": 2,
      "name": "Hoàn thành khóa tập huấn chuyên môn, bồi dưỡng SGK và đổi mới phương pháp dạy học theo CT GDPT 2018 trong hè",
      "spcvFull": "N3_652 - Xây dựng Kế hoạch đào tạo, bồi dưỡng công chức, viên chức",
      "spcvCode": "N3_652",
      "spcvName": "Xây dựng Kế hoạch đào tạo, bồi dưỡng công chức, viên chức",
      "deadline": "15/08/2026",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Giấy chứng nhận / kết quả hoàn thành tập huấn bồi dưỡng hè 2026"
    },
    {
      "id": "GV_6",
      "role": "GV",
      "roleName": "Giáo viên (Bộ môn / Chủ nhiệm / Tổ trưởng)",
      "tt": 1,
      "name": "Xây dựng Kế hoạch dạy học môn học cá nhân năm học 2026 - 2027 nộp Tổ trưởng chuyên môn phê duyệt",
      "spcvFull": "N1_550 - Soạn thảo văn bản hành chính",
      "spcvCode": "N1_550",
      "spcvName": "Soạn thảo văn bản hành chính",
      "deadline": "25/08/2026",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Kế hoạch dạy học cá nhân năm học 2026-2027 có xác nhận của Tổ trưởng"
    },
    {
      "id": "GV_7",
      "role": "GV",
      "roleName": "Giáo viên (Bộ môn / Chủ nhiệm / Tổ trưởng)",
      "tt": 1,
      "name": "Nhận lớp chủ nhiệm, tổ chức cho học sinh tựu trường, ổn định tổ chức lớp và phổ biến nội quy học sinh",
      "spcvFull": "N1_565 - Quản lý, cập nhật cơ sở dữ liệu học sinh",
      "spcvCode": "N1_565",
      "spcvName": "Quản lý, cập nhật cơ sở dữ liệu học sinh",
      "deadline": "28/08/2026",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Biên bản họp lớp đầu năm và danh sách ban cán sự lớp"
    },
    {
      "id": "GV_8",
      "role": "GV",
      "roleName": "Giáo viên (Bộ môn / Chủ nhiệm / Tổ trưởng)",
      "tt": 2,
      "name": "Chuẩn bị trang phục, hướng dẫn học sinh tham gia Lễ Khai giảng năm học 2026 - 2027 trang nghiêm, đầy đủ quân số",
      "spcvFull": "N1_565 - Quản lý, cập nhật cơ sở dữ liệu học sinh",
      "spcvCode": "N1_565",
      "spcvName": "Quản lý, cập nhật cơ sở dữ liệu học sinh",
      "deadline": "05/09/2026",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Sổ chủ nhiệm ghi nhận quân số dự Khai giảng 100%"
    },
    {
      "id": "GV_9",
      "role": "GV",
      "roleName": "Giáo viên (Bộ môn / Chủ nhiệm / Tổ trưởng)",
      "tt": 3,
      "name": "Tổ chức Hội nghị Ban đại diện Cha mẹ học sinh lớp đầu năm học 2026 - 2027; lập biên bản họp đúng quy định",
      "spcvFull": "N1_565 - Quản lý, cập nhật cơ sở dữ liệu học sinh",
      "spcvCode": "N1_565",
      "spcvName": "Quản lý, cập nhật cơ sở dữ liệu học sinh",
      "deadline": "15/09/2026",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Biên bản họp phụ huynh học sinh đầu năm học 2026-2027"
    },
    {
      "id": "GV_10",
      "role": "GV",
      "roleName": "Giáo viên (Bộ môn / Chủ nhiệm / Tổ trưởng)",
      "tt": 4,
      "name": "Cập nhật hồ sơ học sinh, hoàn thiện cơ sở dữ liệu lý lịch và thông tin liên lạc của học sinh trên hệ thống VnEdu",
      "spcvFull": "N1_565 - Quản lý, cập nhật cơ sở dữ liệu học sinh",
      "spcvCode": "N1_565",
      "spcvName": "Quản lý, cập nhật cơ sở dữ liệu học sinh",
      "deadline": "30/09/2026",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Dữ liệu hồ sơ học sinh lớp chủ nhiệm trên hệ thống CSDL trường"
    },
    {
      "id": "GV_11",
      "role": "GV",
      "roleName": "Giáo viên (Bộ môn / Chủ nhiệm / Tổ trưởng)",
      "tt": 2,
      "name": "Soạn Kế hoạch bài dạy (giáo án) các tuần học tháng 9/2026 đúng chuẩn Công văn 5512/BGDĐT, tích hợp năng lực số và AI",
      "spcvFull": "N1_550 - Soạn thảo văn bản hành chính",
      "spcvCode": "N1_550",
      "spcvName": "Soạn thảo văn bản hành chính",
      "deadline": "05/09/2026",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Giáo án các tuần 1, 2, 3, 4 tháng 9 lưu trên hệ thống CSDL giáo án"
    },
    {
      "id": "GV_12",
      "role": "GV",
      "roleName": "Giáo viên (Bộ môn / Chủ nhiệm / Tổ trưởng)",
      "tt": 3,
      "name": "Thiết kế bài giảng điện tử và học liệu số tương tác phục vụ dạy học các chuyên đề đầu năm học mới",
      "spcvFull": "N1_550 - Soạn thảo văn bản hành chính",
      "spcvCode": "N1_550",
      "spcvName": "Soạn thảo văn bản hành chính",
      "deadline": "20/09/2026",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Link bài giảng điện tử và học liệu số tải lên thư viện trường"
    },
    {
      "id": "GV_13",
      "role": "GV",
      "roleName": "Giáo viên (Bộ môn / Chủ nhiệm / Tổ trưởng)",
      "tt": 1,
      "name": "Thực hiện nghiêm túc thời khóa biểu tháng 9/2026, lên lớp đúng giờ, duy trì tốt nền nếp và kỷ luật dạy học",
      "spcvFull": "N2_1115 - Kế hoạch triển khai hoạt động chuyên môn",
      "spcvCode": "N2_1115",
      "spcvName": "Kế hoạch triển khai hoạt động chuyên môn",
      "deadline": "30/09/2026",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Sổ đầu bài các lớp giảng dạy tháng 9/2026"
    },
    {
      "id": "GV_14",
      "role": "GV",
      "roleName": "Giáo viên (Bộ môn / Chủ nhiệm / Tổ trưởng)",
      "tt": 2,
      "name": "Tham gia các buổi sinh hoạt tổ chuyên môn đầu năm học: thống nhất ma trận đề, kế hoạch giáo dục và quy chế tổ",
      "spcvFull": "N2_1115 - Kế hoạch triển khai hoạt động chuyên môn",
      "spcvCode": "N2_1115",
      "spcvName": "Kế hoạch triển khai hoạt động chuyên môn",
      "deadline": "15/09/2026",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Biên bản họp tổ chuyên môn tháng 9/2026"
    },
    {
      "id": "GV_15",
      "role": "GV",
      "roleName": "Giáo viên (Bộ môn / Chủ nhiệm / Tổ trưởng)",
      "tt": 3,
      "name": "Thực hiện dự giờ đồng nghiệp tháng 9 theo kế hoạch tổ chuyên môn (đạt 2 tiết/tháng), trao đổi kinh nghiệm sư phạm",
      "spcvFull": "N2_1115 - Kế hoạch triển khai hoạt động chuyên môn",
      "spcvCode": "N2_1115",
      "spcvName": "Kế hoạch triển khai hoạt động chuyên môn",
      "deadline": "28/09/2026",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Sổ dự giờ giáo viên có nhận xét và đánh giá tiết dạy"
    },
    {
      "id": "GV_16",
      "role": "GV",
      "roleName": "Giáo viên (Bộ môn / Chủ nhiệm / Tổ trưởng)",
      "tt": 3,
      "name": "Thực hiện kiểm tra đánh giá thường xuyên học sinh theo đúng kế hoạch; chấm bài và vào điểm VnEdu kịp thời",
      "spcvFull": "N1_564 - Quản lý dữ liệu của các Kỳ thi",
      "spcvCode": "N1_564",
      "spcvName": "Quản lý dữ liệu của các Kỳ thi",
      "deadline": "30/09/2026",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Điểm kiểm tra thường xuyên tháng 9 cập nhật trên VnEdu"
    },
    {
      "id": "GV_17",
      "role": "GV",
      "roleName": "Giáo viên (Bộ môn / Chủ nhiệm / Tổ trưởng)",
      "tt": 1,
      "name": "Khảo sát chất lượng đầu năm, phát hiện và lập danh sách học sinh năng khiếu để bồi dưỡng đội tuyển HSG môn phụ trách",
      "spcvFull": "N2_1108 - Tổ chức kỳ thi chọn Đội tuyển tham dự kỳ thi chọn học sinh giỏi quốc gia THPT năm học 2026 - 2027 (tổ chức ra đề, coi thi, chấm ",
      "spcvCode": "N2_1108",
      "spcvName": "Tổ chức kỳ thi chọn Đội tuyển tham dự kỳ thi chọn học sinh giỏi quốc gia THPT năm học 2026",
      "deadline": "25/09/2026",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Danh sách đội tuyển HSG và Kế hoạch bồi dưỡng HSG"
    },
    {
      "id": "GV_18",
      "role": "GV",
      "roleName": "Giáo viên (Bộ môn / Chủ nhiệm / Tổ trưởng)",
      "tt": 2,
      "name": "Lập danh sách học sinh học lực yếu kém đầu năm học để xây dựng phương án dạy phụ đạo, kèm cặp nâng cao chất lượng",
      "spcvFull": "N2_1108 - Tổ chức kỳ thi chọn Đội tuyển tham dự kỳ thi chọn học sinh giỏi quốc gia THPT năm học 2026 - 2027 (tổ chức ra đề, coi thi, chấm ",
      "spcvCode": "N2_1108",
      "spcvName": "Tổ chức kỳ thi chọn Đội tuyển tham dự kỳ thi chọn học sinh giỏi quốc gia THPT năm học 2026",
      "deadline": "30/09/2026",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Kế hoạch phụ đạo học sinh có kết quả khảo sát đầu năm thấp"
    },
    {
      "id": "GV_19",
      "role": "GV",
      "roleName": "Giáo viên (Bộ môn / Chủ nhiệm / Tổ trưởng)",
      "tt": 2,
      "name": "Đăng ký tên đề tài Sáng kiến kinh nghiệm hoặc Đề tài nghiên cứu khoa học sư phạm ứng dụng năm học 2026 - 2027",
      "spcvFull": "N3_658 - Thẩm định hồ sơ và tham mưu công tác sáng kiến, đề tài nghiên cứu khoa học; các cuộc thi về công tác học sinh sinh viên; hồ sơ b",
      "spcvCode": "N3_658",
      "spcvName": "Thẩm định hồ sơ và tham mưu công tác sáng kiến, đề tài nghiên cứu khoa học; các cuộc thi về công tác học sinh sinh viên; hồ sơ b",
      "deadline": "25/09/2026",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Phiếu đăng ký đề tài SKKN năm học 2026-2027 nộp Tổ chuyên môn"
    },
    {
      "id": "GV_20",
      "role": "GV",
      "roleName": "Giáo viên (Bộ môn / Chủ nhiệm / Tổ trưởng)",
      "tt": 3,
      "name": "Xây dựng Kế hoạch tự bồi dưỡng thường xuyên cá nhân năm học 2026 - 2027 theo quy định của Bộ và Sở GD&ĐT",
      "spcvFull": "N3_652 - Xây dựng Kế hoạch đào tạo, bồi dưỡng công chức, viên chức",
      "spcvCode": "N3_652",
      "spcvName": "Xây dựng Kế hoạch đào tạo, bồi dưỡng công chức, viên chức",
      "deadline": "25/09/2026",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Bản kế hoạch tự học, bồi dưỡng thường xuyên năm học 2026-2027"
    }
  ],
  "nv": [
    {
      "id": "NV_1",
      "role": "NV",
      "roleName": "Nhân viên (Kế toán / Văn thư / Thiết bị / Y tế / CNTT)",
      "tt": 1,
      "name": "Rút dự toán thanh toán tiền lương, các khoản phụ cấp tháng 6/2026 cho cán bộ, giáo viên, nhân viên đúng thời hạn",
      "spcvFull": "N1_599 - Thực hiện giao dịch kho bạc , ngân hàng",
      "spcvCode": "N1_599",
      "spcvName": "Thực hiện giao dịch kho bạc , ngân hàng",
      "deadline": "10/06/2026",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Giấy rút dự toán ngân sách và bảng thanh toán lương tháng 6/2026"
    },
    {
      "id": "NV_2",
      "role": "NV",
      "roleName": "Nhân viên (Kế toán / Văn thư / Thiết bị / Y tế / CNTT)",
      "tt": 1,
      "name": "Tiếp nhận, đăng ký, chuyển giao kịp thời văn bản chỉ đạo của Sở về thi tốt nghiệp THPT và tuyển sinh lớp 10 năm 2026",
      "spcvFull": "N1_602 - Quản lý và xử lý văn bản đi, đến (Chính quyền + Đảng ủy)",
      "spcvCode": "N1_602",
      "spcvName": "Quản lý và xử lý văn bản đi, đến (Chính quyền + Đảng ủy)",
      "deadline": "20/06/2026",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Sổ theo dõi văn bản đến tháng 6/2026 trên iOffice"
    },
    {
      "id": "NV_3",
      "role": "NV",
      "roleName": "Nhân viên (Kế toán / Văn thư / Thiết bị / Y tế / CNTT)",
      "tt": 1,
      "name": "Chuẩn bị cơ số thuốc, vật tư y tế, phòng y tế phục vụ Điểm thi tốt nghiệp THPT năm 2026 tại trường an toàn",
      "spcvFull": "N2_1066 - Báo cáo công tác xây dựng giáo dục môi trường an toàn lành mạnh và phòng chống bạo lực học đường",
      "spcvCode": "N2_1066",
      "spcvName": "Báo cáo công tác xây dựng giáo dục môi trường an toàn lành mạnh và phòng chống bạo lực học đường",
      "deadline": "22/06/2026",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Biên bản kiểm tra điều kiện y tế phục vụ kỳ thi tốt nghiệp 2026"
    },
    {
      "id": "NV_4",
      "role": "NV",
      "roleName": "Nhân viên (Kế toán / Văn thư / Thiết bị / Y tế / CNTT)",
      "tt": 1,
      "name": "Bảo dưỡng, kiểm tra hệ thống máy vi tính, đường truyền internet, camera giám sát phục vụ thi tốt nghiệp THPT 2026",
      "spcvFull": "N2_1085 - Triển khai cảnh báo các lỗ hổng bảo mật, an toàn thông tin theo hướng dẫn của cơ quan chuyên môn",
      "spcvCode": "N2_1085",
      "spcvName": "Triển khai cảnh báo các lỗ hổng bảo mật, an toàn thông tin theo hướng dẫn của cơ quan chuyên môn",
      "deadline": "20/06/2026",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Nhật ký kiểm tra thiết bị CNTT phục vụ kỳ thi"
    },
    {
      "id": "NV_5",
      "role": "NV",
      "roleName": "Nhân viên (Kế toán / Văn thư / Thiết bị / Y tế / CNTT)",
      "tt": 1,
      "name": "Thu hồi SGK, tài liệu tham khảo cho mượn năm học 2025 - 2026; xử lý kỹ thuật và sắp xếp lại kho sách thư viện",
      "spcvFull": "N2_1067 - Báo cáo kết quả tổ chức thực hiện ngày Sách và Văn hóa đọc Việt Nam năm 2026",
      "spcvCode": "N2_1067",
      "spcvName": "Báo cáo kết quả tổ chức thực hiện ngày Sách và Văn hóa đọc Việt Nam năm 2026",
      "deadline": "28/06/2026",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Sổ theo dõi mượn trả sách thư viện cuối năm"
    },
    {
      "id": "NV_6",
      "role": "NV",
      "roleName": "Nhân viên (Kế toán / Văn thư / Thiết bị / Y tế / CNTT)",
      "tt": 2,
      "name": "Thực hiện đối chiếu số dư tài khoản tiền gửi và hạn mức kinh phí 6 tháng đầu năm 2026 với Kho bạc Nhà nước",
      "spcvFull": "N1_599 - Thực hiện giao dịch kho bạc , ngân hàng",
      "spcvCode": "N1_599",
      "spcvName": "Thực hiện giao dịch kho bạc , ngân hàng",
      "deadline": "10/07/2026",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Biên bản đối chiếu tài khoản với KBNN kỳ 6 tháng đầu năm 2026"
    },
    {
      "id": "NV_7",
      "role": "NV",
      "roleName": "Nhân viên (Kế toán / Văn thư / Thiết bị / Y tế / CNTT)",
      "tt": 1,
      "name": "Lập báo cáo tài chính và báo cáo quyết toán ngân sách nhà nước 6 tháng đầu năm 2026 nộp Sở GD&ĐT",
      "spcvFull": "N3_695 - Tổng hợp và lập báo cáo tài chính hợp nhất, báo cáo quyết toán năm",
      "spcvCode": "N3_695",
      "spcvName": "Tổng hợp và lập báo cáo tài chính hợp nhất, báo cáo quyết toán năm",
      "deadline": "15/07/2026",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Báo cáo quyết toán ngân sách 6 tháng đầu năm 2026"
    },
    {
      "id": "NV_8",
      "role": "NV",
      "roleName": "Nhân viên (Kế toán / Văn thư / Thiết bị / Y tế / CNTT)",
      "tt": 1,
      "name": "Tiếp nhận hồ sơ, sao lục học bạ và cấp phát giấy chứng nhận tốt nghiệp tạm thời cho học sinh khối 12 năm 2026",
      "spcvFull": "N1_603 - Quản lý và sử dụng con dấu, thiết bị lưu khóa bí mật; thực hiện ký số chuyển thủ tục hành chính trên dịch vụ công",
      "spcvCode": "N1_603",
      "spcvName": "Quản lý và sử dụng con dấu, thiết bị lưu khóa bí mật; thực hiện ký số chuyển thủ tục hành chính trên dịch vụ công",
      "deadline": "15/07/2026",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Sổ cấp phát văn bằng chứng chỉ, giấy chứng nhận tốt nghiệp tạm thời"
    },
    {
      "id": "NV_9",
      "role": "NV",
      "roleName": "Nhân viên (Kế toán / Văn thư / Thiết bị / Y tế / CNTT)",
      "tt": 1,
      "name": "Thu thập, phân loại và lưu trữ toàn bộ hồ sơ thi tốt nghiệp THPT 2026, hồ sơ tuyển sinh 10 và hồ sơ thi đua năm học 2025 - 2026",
      "spcvFull": "N1_604 - Thu thập hồ sơ tài liệu vào kho lưu trữ, phục vụ khai thác, sử dụng tài liệu lưu trữ",
      "spcvCode": "N1_604",
      "spcvName": "Thu thập hồ sơ tài liệu vào kho lưu trữ, phục vụ khai thác, sử dụng tài liệu lưu trữ",
      "deadline": "31/07/2026",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Mục lục hồ sơ tài liệu nộp lưu trữ cơ quan đợt hè 2026"
    },
    {
      "id": "NV_10",
      "role": "NV",
      "roleName": "Nhân viên (Kế toán / Văn thư / Thiết bị / Y tế / CNTT)",
      "tt": 1,
      "name": "Chi trả kịp thời tiền làm nhiệm vụ coi thi, chấm thi và tiền phụ cấp làm việc hè cho cán bộ, giáo viên đúng danh sách",
      "spcvFull": "N1_605 - Quản lý thu, chi tiền mặt tại quỹ, Kiêm nhiệm Thủ quỹ cơ quan; thực hiện các giao dịch tại Kho bạc/Ngân hàng",
      "spcvCode": "N1_605",
      "spcvName": "Quản lý thu, chi tiền mặt tại quỹ, Kiêm nhiệm Thủ quỹ cơ quan; thực hiện các giao dịch tại Kho bạc/Ngân hàng",
      "deadline": "30/07/2026",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Bảng thanh toán tiền làm nhiệm vụ thi có chữ ký người nhận"
    },
    {
      "id": "NV_11",
      "role": "NV",
      "roleName": "Nhân viên (Kế toán / Văn thư / Thiết bị / Y tế / CNTT)",
      "tt": 2,
      "name": "Lập dự toán kinh phí mua sắm, sửa chữa cơ sở vật chất, bàn ghế phục vụ khai giảng và năm học mới 2026 - 2027",
      "spcvFull": "N3_695 - Tổng hợp và lập báo cáo tài chính hợp nhất, báo cáo quyết toán năm",
      "spcvCode": "N3_695",
      "spcvName": "Tổng hợp và lập báo cáo tài chính hợp nhất, báo cáo quyết toán năm",
      "deadline": "15/08/2026",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Dự toán chi tiết mua sắm, sửa chữa CSVC đầu năm học mới"
    },
    {
      "id": "NV_12",
      "role": "NV",
      "roleName": "Nhân viên (Kế toán / Văn thư / Thiết bị / Y tế / CNTT)",
      "tt": 1,
      "name": "Kiểm kê, vệ sinh, bảo dưỡng toàn bộ thiết bị dạy học, hóa chất, phòng thực hành Lý, Hóa, Sinh trong dịp hè",
      "spcvFull": "N4_182 - Tham mưu Quyết đinh quy định định tiêu chuẩn, định mức về máy móc thiết bị dạy học",
      "spcvCode": "N4_182",
      "spcvName": "Tham mưu Quyết đinh quy định định tiêu chuẩn, định mức về máy móc thiết bị dạy học",
      "deadline": "15/08/2026",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Biên bản kiểm kê thiết bị dạy học và phòng bộ môn hè 2026"
    },
    {
      "id": "NV_13",
      "role": "NV",
      "roleName": "Nhân viên (Kế toán / Văn thư / Thiết bị / Y tế / CNTT)",
      "tt": 2,
      "name": "Tiếp nhận, đóng dấu nghiệp vụ và cấp phát SGK mới, tài liệu hướng dẫn giảng dạy cho GV và HS chuẩn bị năm học mới",
      "spcvFull": "N2_1067 - Báo cáo kết quả tổ chức thực hiện ngày Sách và Văn hóa đọc Việt Nam năm 2026",
      "spcvCode": "N2_1067",
      "spcvName": "Báo cáo kết quả tổ chức thực hiện ngày Sách và Văn hóa đọc Việt Nam năm 2026",
      "deadline": "25/08/2026",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Sổ đăng ký cá biệt và danh sách cấp phát sách giáo khoa mới"
    },
    {
      "id": "NV_14",
      "role": "NV",
      "roleName": "Nhân viên (Kế toán / Văn thư / Thiết bị / Y tế / CNTT)",
      "tt": 2,
      "name": "Bảo dưỡng phòng máy tính tin học, kiểm tra tài khoản VnEdu, CSDL ngành, học bạ số và chữ ký số chuẩn bị năm học mới",
      "spcvFull": "N2_1085 - Triển khai cảnh báo các lỗ hổng bảo mật, an toàn thông tin theo hướng dẫn của cơ quan chuyên môn",
      "spcvCode": "N2_1085",
      "spcvName": "Triển khai cảnh báo các lỗ hổng bảo mật, an toàn thông tin theo hướng dẫn của cơ quan chuyên môn",
      "deadline": "25/08/2026",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Biên bản kiểm tra hệ thống CNTT và phần mềm quản lý trường học"
    },
    {
      "id": "NV_15",
      "role": "NV",
      "roleName": "Nhân viên (Kế toán / Văn thư / Thiết bị / Y tế / CNTT)",
      "tt": 3,
      "name": "Lập hồ sơ rút dự toán thanh toán tiền lương, phụ cấp tháng 9/2026 và trích nộp BHXH, BHYT, KPCĐ đúng thời hạn",
      "spcvFull": "N1_599 - Thực hiện giao dịch kho bạc , ngân hàng",
      "spcvCode": "N1_599",
      "spcvName": "Thực hiện giao dịch kho bạc , ngân hàng",
      "deadline": "10/09/2026",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Bảng thanh toán lương tháng 9/2026 và chứng từ nộp bảo hiểm xã hội"
    },
    {
      "id": "NV_16",
      "role": "NV",
      "roleName": "Nhân viên (Kế toán / Văn thư / Thiết bị / Y tế / CNTT)",
      "tt": 2,
      "name": "Kiểm tra thể thức, lấy số, phát hành các quyết định phân công chuyên môn, kế hoạch khai giảng và văn bản đầu năm học",
      "spcvFull": "N1_602 - Quản lý và xử lý văn bản đi, đến (Chính quyền + Đảng ủy)",
      "spcvCode": "N1_602",
      "spcvName": "Quản lý và xử lý văn bản đi, đến (Chính quyền + Đảng ủy)",
      "deadline": "05/09/2026",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Sổ theo dõi văn bản đi tháng 9/2026"
    },
    {
      "id": "NV_17",
      "role": "NV",
      "roleName": "Nhân viên (Kế toán / Văn thư / Thiết bị / Y tế / CNTT)",
      "tt": 2,
      "name": "Quản lý con dấu, chứng thư số; thực hiện đóng dấu giấy xác nhận học sinh, chứng chỉ cho học sinh đầu năm đúng quy định",
      "spcvFull": "N1_603 - Quản lý và sử dụng con dấu, thiết bị lưu khóa bí mật; thực hiện ký số chuyển thủ tục hành chính trên dịch vụ công",
      "spcvCode": "N1_603",
      "spcvName": "Quản lý và sử dụng con dấu, thiết bị lưu khóa bí mật; thực hiện ký số chuyển thủ tục hành chính trên dịch vụ công",
      "deadline": "20/09/2026",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Sổ cấp giấy xác nhận học sinh năm học 2026-2027"
    },
    {
      "id": "NV_18",
      "role": "NV",
      "roleName": "Nhân viên (Kế toán / Văn thư / Thiết bị / Y tế / CNTT)",
      "tt": 2,
      "name": "Mở sổ quỹ tiền mặt năm học 2026 - 2027, ghi chép thu chi quỹ tháng 9 chính xác, thực hiện kiểm kê quỹ cuối tháng",
      "spcvFull": "N1_605 - Quản lý thu, chi tiền mặt tại quỹ, Kiêm nhiệm Thủ quỹ cơ quan; thực hiện các giao dịch tại Kho bạc/Ngân hàng",
      "spcvCode": "N1_605",
      "spcvName": "Quản lý thu, chi tiền mặt tại quỹ, Kiêm nhiệm Thủ quỹ cơ quan; thực hiện các giao dịch tại Kho bạc/Ngân hàng",
      "deadline": "30/09/2026",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Sổ quỹ tiền mặt tháng 9/2026 có xác nhận của Kế toán và Hiệu trưởng"
    },
    {
      "id": "NV_19",
      "role": "NV",
      "roleName": "Nhân viên (Kế toán / Văn thư / Thiết bị / Y tế / CNTT)",
      "tt": 2,
      "name": "Lập kế hoạch sử dụng phòng học bộ môn và chuẩn bị đầy đủ thiết bị, hóa chất phục vụ các tiết dạy thực hành tháng 9",
      "spcvFull": "N4_182 - Tham mưu Quyết đinh quy định định tiêu chuẩn, định mức về máy móc thiết bị dạy học",
      "spcvCode": "N4_182",
      "spcvName": "Tham mưu Quyết đinh quy định định tiêu chuẩn, định mức về máy móc thiết bị dạy học",
      "deadline": "15/09/2026",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Sổ mượn trả thiết bị dạy học tháng 9/2026"
    },
    {
      "id": "NV_20",
      "role": "NV",
      "roleName": "Nhân viên (Kế toán / Văn thư / Thiết bị / Y tế / CNTT)",
      "tt": 2,
      "name": "Kiểm tra tủ thuốc y tế, bổ sung bông băng thuốc thiết yếu và lập kế hoạch chăm sóc sức khỏe học sinh đầu năm học mới",
      "spcvFull": "N2_1066 - Báo cáo công tác xây dựng giáo dục môi trường an toàn lành mạnh và phòng chống bạo lực học đường",
      "spcvCode": "N2_1066",
      "spcvName": "Báo cáo công tác xây dựng giáo dục môi trường an toàn lành mạnh và phòng chống bạo lực học đường",
      "deadline": "10/09/2026",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Kế hoạch y tế học đường năm học 2026-2027 và danh mục thuốc"
    },
    {
      "id": "NV_21",
      "role": "NV",
      "roleName": "Nhân viên (Kế toán / Văn thư / Thiết bị / Y tế / CNTT)",
      "tt": 3,
      "name": "Tuyên truyền phòng chống sốt xuất huyết, dịch bệnh mùa thu và phối hợp vận động học sinh tham gia BHYT đạt 100%",
      "spcvFull": "N2_1066 - Báo cáo công tác xây dựng giáo dục môi trường an toàn lành mạnh và phòng chống bạo lực học đường",
      "spcvCode": "N2_1066",
      "spcvName": "Báo cáo công tác xây dựng giáo dục môi trường an toàn lành mạnh và phòng chống bạo lực học đường",
      "deadline": "30/09/2026",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Báo cáo công tác BHYT học sinh tháng 9/2026"
    },
    {
      "id": "NV_22",
      "role": "NV",
      "roleName": "Nhân viên (Kế toán / Văn thư / Thiết bị / Y tế / CNTT)",
      "tt": 3,
      "name": "Đưa tin bài, hình ảnh Lễ Khai giảng năm học 2026 - 2027 lên website trường; sao lưu an toàn CSDL tháng 9/2026",
      "spcvFull": "N2_1085 - Triển khai cảnh báo các lỗ hổng bảo mật, an toàn thông tin theo hướng dẫn của cơ quan chuyên môn",
      "spcvCode": "N2_1085",
      "spcvName": "Triển khai cảnh báo các lỗ hổng bảo mật, an toàn thông tin theo hướng dẫn của cơ quan chuyên môn",
      "deadline": "25/09/2026",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Link bài viết trên website trường và file nhật ký sao lưu hệ thống"
    }
  ]
};

export const ALL_JOBS: JobItem[] = [
  ...JOBS_DATA.cbql,
  ...JOBS_DATA.gv,
  ...JOBS_DATA.nv
];
