// Danh mục công việc chính thức CBQL - GV - NV phục vụ Đánh giá xếp loại viên chức
export interface JobItem {
  id: string;
  role: 'CBQL' | 'GV' | 'NV';
  roleName: string;
  tt: number;
  name: string;
  spcvFull: string;
  spcvCode: string;
  spcvName: string;
  deadline: string;
  targetQuantity: number;
  targetQuality: number;
  targetProgress: number;
  notes: string;
}

export const JOBS_DATA: {
  cbql: JobItem[];
  gv: JobItem[];
  nv: JobItem[];
} = {
  "cbql": [
    {
      "id": "CBQL_1",
      "role": "CBQL",
      "roleName": "Cán bộ Quản lý (BGH)",
      "tt": 1,
      "name": "Xây dựng và ban hành Kế hoạch giáo dục nhà trường, kế hoạch phát triển chiến lược năm học 2026 - 2027",
      "spcvFull": "N3_668 - Quyết định ban hành Kế hoạch nhiệm vụ, giải pháp trọng tâm năm học 2026 - 2027 của ngành Giáo dục tỉnh Cao Bằng",
      "spcvCode": "N3_668",
      "spcvName": "Quyết định ban hành Kế hoạch nhiệm vụ, giải pháp trọng tâm năm học 2026",
      "deadline": "15/09/2026",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Kế hoạch số 01/KH-THPT; Nghị quyết Hội đồng trường"
    },
    {
      "id": "CBQL_2",
      "role": "CBQL",
      "roleName": "Cán bộ Quản lý (BGH)",
      "tt": 2,
      "name": "Phê duyệt kế hoạch giáo dục của các tổ chuyên môn, tổ văn phòng và các tổ chức đoàn thể trong nhà trường",
      "spcvFull": "N3_668 - Quyết định ban hành Kế hoạch nhiệm vụ, giải pháp trọng tâm năm học 2026 - 2027 của ngành Giáo dục tỉnh Cao Bằng",
      "spcvCode": "N3_668",
      "spcvName": "Quyết định ban hành Kế hoạch nhiệm vụ, giải pháp trọng tâm năm học 2026",
      "deadline": "30/09/2026",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Kế hoạch năm học các tổ TN, XH, VP, Công đoàn, Đoàn TN"
    },
    {
      "id": "CBQL_3",
      "role": "CBQL",
      "roleName": "Cán bộ Quản lý (BGH)",
      "tt": 3,
      "name": "Chỉ đạo tổ chức Hội nghị cán bộ, viên chức, người lao động năm học 2026 - 2027",
      "spcvFull": "N3_668 - Quyết định ban hành Kế hoạch nhiệm vụ, giải pháp trọng tâm năm học 2026 - 2027 của ngành Giáo dục tỉnh Cao Bằng",
      "spcvCode": "N3_668",
      "spcvName": "Quyết định ban hành Kế hoạch nhiệm vụ, giải pháp trọng tâm năm học 2026",
      "deadline": "15/10/2026",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Nghị quyết Hội nghị CBVC-NLĐ năm học 2026-2027"
    },
    {
      "id": "CBQL_4",
      "role": "CBQL",
      "roleName": "Cán bộ Quản lý (BGH)",
      "tt": 1,
      "name": "Xây dựng lịch công tác tuần, tháng, quý và chương trình điều hành tổng thể hoạt động sư phạm nhà trường",
      "spcvFull": "N1_610 - Chủ trì xây dựng kế hoạch, chương trình công tác của Phòng",
      "spcvCode": "N1_610",
      "spcvName": "Chủ trì xây dựng kế hoạch, chương trình công tác của Phòng",
      "deadline": "31/05/2027",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Lịch công tác tuần đưa lên website và bảng tin điện tử"
    },
    {
      "id": "CBQL_5",
      "role": "CBQL",
      "roleName": "Cán bộ Quản lý (BGH)",
      "tt": 2,
      "name": "Phân công nhiệm vụ cụ thể cho các Phó Hiệu trưởng, Tổ trưởng chuyên môn và các bộ phận phụ trách",
      "spcvFull": "N1_610 - Chủ trì xây dựng kế hoạch, chương trình công tác của Phòng",
      "spcvCode": "N1_610",
      "spcvName": "Chủ trì xây dựng kế hoạch, chương trình công tác của Phòng",
      "deadline": "10/09/2026",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Quyết định phân công nhiệm vụ cán bộ quản lý năm học"
    },
    {
      "id": "CBQL_6",
      "role": "CBQL",
      "roleName": "Cán bộ Quản lý (BGH)",
      "tt": 1,
      "name": "Tổ chức họp giao ban Ban Giám hiệu và họp Hội đồng sư phạm định kỳ hàng tháng",
      "spcvFull": "N1_611 - Tổ chức, điều hành, đánh giá kết quả thực hiện nhiệm vụ của công chức thuộc phòng",
      "spcvCode": "N1_611",
      "spcvName": "Tổ chức, điều hành, đánh giá kết quả thực hiện nhiệm vụ của công chức thuộc phòng",
      "deadline": "31/05/2027",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Biên bản họp Hội đồng sư phạm từ tháng 9/2026 đến 5/2027"
    },
    {
      "id": "CBQL_7",
      "role": "CBQL",
      "roleName": "Cán bộ Quản lý (BGH)",
      "tt": 2,
      "name": "Chỉ đạo, đôn đốc và đánh giá xếp loại thi đua cán bộ, giáo viên, nhân viên hàng tháng",
      "spcvFull": "N1_611 - Tổ chức, điều hành, đánh giá kết quả thực hiện nhiệm vụ của công chức thuộc phòng",
      "spcvCode": "N1_611",
      "spcvName": "Tổ chức, điều hành, đánh giá kết quả thực hiện nhiệm vụ của công chức thuộc phòng",
      "deadline": "31/05/2027",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Bảng tổng hợp xếp loại thi đua tháng các tổ"
    },
    {
      "id": "CBQL_8",
      "role": "CBQL",
      "roleName": "Cán bộ Quản lý (BGH)",
      "tt": 3,
      "name": "Kiểm tra, đôn đốc tiến độ thực hiện chương trình giảng dạy và quy chế chuyên môn toàn trường",
      "spcvFull": "N1_611 - Tổ chức, điều hành, đánh giá kết quả thực hiện nhiệm vụ của công chức thuộc phòng",
      "spcvCode": "N1_611",
      "spcvName": "Tổ chức, điều hành, đánh giá kết quả thực hiện nhiệm vụ của công chức thuộc phòng",
      "deadline": "31/05/2027",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Hồ sơ theo dõi tiến độ chương trình trên hệ thống VnEdu"
    },
    {
      "id": "CBQL_9",
      "role": "CBQL",
      "roleName": "Cán bộ Quản lý (BGH)",
      "tt": 1,
      "name": "Ban hành Bộ tiêu chí và quy định đánh giá, xếp loại viên chức, người lao động năm học 2026 - 2027",
      "spcvFull": "N2_1046 - Tham mưu công tác đánh giá, xếp loại",
      "spcvCode": "N2_1046",
      "spcvName": "Tham mưu công tác đánh giá, xếp loại",
      "deadline": "15/10/2026",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Quy định số 02/QĐ-THPT về tiêu chí thi đua xếp loại"
    },
    {
      "id": "CBQL_10",
      "role": "CBQL",
      "roleName": "Cán bộ Quản lý (BGH)",
      "tt": 2,
      "name": "Thành lập Hội đồng đánh giá, phân loại chất lượng viên chức và người lao động nhà trường",
      "spcvFull": "N2_1046 - Tham mưu công tác đánh giá, xếp loại",
      "spcvCode": "N2_1046",
      "spcvName": "Tham mưu công tác đánh giá, xếp loại",
      "deadline": "15/05/2027",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Quyết định thành lập Hội đồng ĐGXL viên chức"
    },
    {
      "id": "CBQL_11",
      "role": "CBQL",
      "roleName": "Cán bộ Quản lý (BGH)",
      "tt": 3,
      "name": "Tổ chức đánh giá, tổng hợp kết quả và ban hành quyết định công nhận xếp loại viên chức cuối năm",
      "spcvFull": "N2_1046 - Tham mưu công tác đánh giá, xếp loại",
      "spcvCode": "N2_1046",
      "spcvName": "Tham mưu công tác đánh giá, xếp loại",
      "deadline": "31/05/2027",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Biên bản họp xét thi đua và Thông báo kết quả ĐGXL"
    },
    {
      "id": "CBQL_12",
      "role": "CBQL",
      "roleName": "Cán bộ Quản lý (BGH)",
      "tt": 1,
      "name": "Xây dựng và triển khai Kế hoạch kiểm tra nội bộ trường học năm học 2026 - 2027 (toàn diện & chuyên đề)",
      "spcvFull": "N2_1042 - Tham mưu công tác kiểm tra các kỳ thi, kiểm tra chuyên môn",
      "spcvCode": "N2_1042",
      "spcvName": "Tham mưu công tác kiểm tra các kỳ thi, kiểm tra chuyên môn",
      "deadline": "30/09/2026",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Kế hoạch số 03/KH-KTNB và các biên bản kiểm tra chuyên đề"
    },
    {
      "id": "CBQL_13",
      "role": "CBQL",
      "roleName": "Cán bộ Quản lý (BGH)",
      "tt": 2,
      "name": "Kiểm tra hồ sơ chuyên môn, giáo án điện tử, sổ điểm và nền nếp dạy học của giáo viên",
      "spcvFull": "N2_1042 - Tham mưu công tác kiểm tra các kỳ thi, kiểm tra chuyên môn",
      "spcvCode": "N2_1042",
      "spcvName": "Tham mưu công tác kiểm tra các kỳ thi, kiểm tra chuyên môn",
      "deadline": "31/05/2027",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Biên bản kiểm tra hồ sơ giáo viên định kỳ 2 lần/học kỳ"
    },
    {
      "id": "CBQL_14",
      "role": "CBQL",
      "roleName": "Cán bộ Quản lý (BGH)",
      "tt": 3,
      "name": "Chỉ đạo và giám sát công tác tổ chức kiểm tra định kỳ (giữa kỳ, cuối kỳ) và thi thử tốt nghiệp THPT",
      "spcvFull": "N2_1042 - Tham mưu công tác kiểm tra các kỳ thi, kiểm tra chuyên môn",
      "spcvCode": "N2_1042",
      "spcvName": "Tham mưu công tác kiểm tra các kỳ thi, kiểm tra chuyên môn",
      "deadline": "31/05/2027",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Kế hoạch kiểm tra định kỳ và biên bản giám sát coi, chấm thi"
    },
    {
      "id": "CBQL_15",
      "role": "CBQL",
      "roleName": "Cán bộ Quản lý (BGH)",
      "tt": 1,
      "name": "Xây dựng Kế hoạch ôn tập tốt nghiệp THPT năm 2027 cho học sinh khối 12; phân công GV cốt cán phụ trách",
      "spcvFull": "N3_661 - Ban hành Kế hoạch tổ chức kỳ thi tốt nghiệp THPT năm 2026 của Sở GDĐT",
      "spcvCode": "N3_661",
      "spcvName": "Ban hành Kế hoạch tổ chức kỳ thi tốt nghiệp THPT năm 2026 của Sở GDĐT",
      "deadline": "15/11/2026",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Kế hoạch ôn tập tốt nghiệp THPT năm học 2026-2027"
    },
    {
      "id": "CBQL_16",
      "role": "CBQL",
      "roleName": "Cán bộ Quản lý (BGH)",
      "tt": 2,
      "name": "Tổ chức các đợt thi thử tốt nghiệp THPT, phân tích phổ điểm để chỉ đạo đổi mới phương pháp dạy ôn",
      "spcvFull": "N3_661 - Ban hành Kế hoạch tổ chức kỳ thi tốt nghiệp THPT năm 2026 của Sở GDĐT",
      "spcvCode": "N3_661",
      "spcvName": "Ban hành Kế hoạch tổ chức kỳ thi tốt nghiệp THPT năm 2026 của Sở GDĐT",
      "deadline": "20/05/2027",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Báo cáo phân tích phổ điểm các đợt thi khảo sát khối 12"
    },
    {
      "id": "CBQL_17",
      "role": "CBQL",
      "roleName": "Cán bộ Quản lý (BGH)",
      "tt": 3,
      "name": "Chuẩn bị đầy đủ các điều kiện cơ sở vật chất, an ninh trật tự phục vụ Điểm thi tốt nghiệp THPT",
      "spcvFull": "N3_661 - Ban hành Kế hoạch tổ chức kỳ thi tốt nghiệp THPT năm 2026 của Sở GDĐT",
      "spcvCode": "N3_661",
      "spcvName": "Ban hành Kế hoạch tổ chức kỳ thi tốt nghiệp THPT năm 2026 của Sở GDĐT",
      "deadline": "20/06/2027",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Biên bản kiểm tra cơ sở vật chất Điểm thi tốt nghiệp"
    },
    {
      "id": "CBQL_18",
      "role": "CBQL",
      "roleName": "Cán bộ Quản lý (BGH)",
      "tt": 1,
      "name": "Chỉ đạo xây dựng dự toán ngân sách Nhà nước và Quy chế chi tiêu nội bộ năm học 2026 - 2027",
      "spcvFull": "N2_1150 - Xây dựng dự toán ngân sách Nhà nước hàng năm",
      "spcvCode": "N2_1150",
      "spcvName": "Xây dựng dự toán ngân sách Nhà nước hàng năm",
      "deadline": "31/10/2026",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Dự toán ngân sách năm 2027 và Quy chế chi tiêu nội bộ sửa đổi"
    },
    {
      "id": "CBQL_19",
      "role": "CBQL",
      "roleName": "Cán bộ Quản lý (BGH)",
      "tt": 2,
      "name": "Quản lý, sử dụng nguồn tài chính ngân sách đúng quy định, công khai minh bạch tài chính trường học",
      "spcvFull": "N2_1150 - Xây dựng dự toán ngân sách Nhà nước hàng năm",
      "spcvCode": "N2_1150",
      "spcvName": "Xây dựng dự toán ngân sách Nhà nước hàng năm",
      "deadline": "31/05/2027",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Báo cáo công khai tài chính định kỳ quý, năm theo Thông tư"
    },
    {
      "id": "CBQL_20",
      "role": "CBQL",
      "roleName": "Cán bộ Quản lý (BGH)",
      "tt": 1,
      "name": "Rà soát, mua sắm bổ sung, sửa chữa cơ sở vật chất, thiết bị dạy học phục vụ năm học mới 2026 - 2027",
      "spcvFull": "N3_684 - Tham mưu triển khai công tác thuộc lĩnh vực Cơ sở vật chất",
      "spcvCode": "N3_684",
      "spcvName": "Tham mưu triển khai công tác thuộc lĩnh vực Cơ sở vật chất",
      "deadline": "05/09/2026",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Biên bản kiểm kê và danh mục mua sắm sửa chữa tài sản"
    },
    {
      "id": "CBQL_21",
      "role": "CBQL",
      "roleName": "Cán bộ Quản lý (BGH)",
      "tt": 2,
      "name": "Chỉ đạo công tác bảo đảm an toàn trường học, phòng chống cháy nổ, vệ sinh môi trường xanh - sạch - đẹp",
      "spcvFull": "N3_684 - Tham mưu triển khai công tác thuộc lĩnh vực Cơ sở vật chất",
      "spcvCode": "N3_684",
      "spcvName": "Tham mưu triển khai công tác thuộc lĩnh vực Cơ sở vật chất",
      "deadline": "31/05/2027",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Kế hoạch an toàn trường học và biên bản tự kiểm tra PCCC"
    },
    {
      "id": "CBQL_22",
      "role": "CBQL",
      "roleName": "Cán bộ Quản lý (BGH)",
      "tt": 1,
      "name": "Ban hành Thông báo Lịch tiếp công dân của Hiệu trưởng, bố trí phòng tiếp dân và mở sổ theo dõi tiếp dân",
      "spcvFull": "N1_572 - Tiếp công dân định kỳ cùng Giám đốc Sở GDĐT",
      "spcvCode": "N1_572",
      "spcvName": "Tiếp công dân định kỳ cùng Giám đốc Sở GDĐT",
      "deadline": "15/09/2026",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Thông báo lịch tiếp công dân năm học 2026-2027"
    },
    {
      "id": "CBQL_23",
      "role": "CBQL",
      "roleName": "Cán bộ Quản lý (BGH)",
      "tt": 2,
      "name": "Thực hiện tiếp công dân định kỳ và đột xuất; xử lý, giải quyết kịp thời đơn thư khiếu nại, phản ánh",
      "spcvFull": "N1_572 - Tiếp công dân định kỳ cùng Giám đốc Sở GDĐT",
      "spcvCode": "N1_572",
      "spcvName": "Tiếp công dân định kỳ cùng Giám đốc Sở GDĐT",
      "deadline": "31/05/2027",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Sổ theo dõi tiếp công dân và giải quyết khiếu nại kiến nghị"
    },
    {
      "id": "CBQL_24",
      "role": "CBQL",
      "roleName": "Cán bộ Quản lý (BGH)",
      "tt": 1,
      "name": "Chỉ đạo triển khai mạnh mẽ ứng dụng CNTT, phần mềm quản lý trường học VnEdu, học bạ số và chữ ký số",
      "spcvFull": "N2_1107 - Báo cáo tổng kết đánh giá tình hình triển khai nhiệm vụ ứng dụng công nghệ thông tin và chuyển đổi số",
      "spcvCode": "N2_1107",
      "spcvName": "Báo cáo tổng kết đánh giá tình hình triển khai nhiệm vụ ứng dụng công nghệ thông tin và chuyển đổi số",
      "deadline": "31/05/2027",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Hồ sơ triển khai 100% học bạ số và chữ ký số giáo viên"
    },
    {
      "id": "CBQL_25",
      "role": "CBQL",
      "roleName": "Cán bộ Quản lý (BGH)",
      "tt": 2,
      "name": "Xây dựng báo cáo tổng kết chuyển đổi số và phát triển kho học liệu điện tử phục vụ giáo viên, học sinh",
      "spcvFull": "N2_1107 - Báo cáo tổng kết đánh giá tình hình triển khai nhiệm vụ ứng dụng công nghệ thông tin và chuyển đổi số",
      "spcvCode": "N2_1107",
      "spcvName": "Báo cáo tổng kết đánh giá tình hình triển khai nhiệm vụ ứng dụng công nghệ thông tin và chuyển đổi số",
      "deadline": "31/05/2027",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Báo cáo chuyển đổi số ngành giáo dục năm học 2026-2027"
    }
  ],
  "gv": [
    {
      "id": "GV_1",
      "role": "GV",
      "roleName": "Giáo viên (Bộ môn / Chủ nhiệm / Tổ trưởng)",
      "tt": 1,
      "name": "Soạn Kế hoạch bài dạy (giáo án) đúng chuẩn Công văn 5512/BGDĐT, tích hợp năng lực số và ứng dụng AI",
      "spcvFull": "N1_550 - Soạn thảo văn bản hành chính",
      "spcvCode": "N1_550",
      "spcvName": "Soạn thảo văn bản hành chính",
      "deadline": "31/05/2027",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Giáo án điện tử môn giảng dạy lưu trên hệ thống CSDL trường"
    },
    {
      "id": "GV_2",
      "role": "GV",
      "roleName": "Giáo viên (Bộ môn / Chủ nhiệm / Tổ trưởng)",
      "tt": 2,
      "name": "Xây dựng Kế hoạch dạy học môn học cá nhân và kế hoạch kiểm tra đánh giá định kỳ theo phân phối chương trình",
      "spcvFull": "N1_550 - Soạn thảo văn bản hành chính",
      "spcvCode": "N1_550",
      "spcvName": "Soạn thảo văn bản hành chính",
      "deadline": "15/09/2026",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "KHDH cá nhân đã được Tổ trưởng và BGH phê duyệt"
    },
    {
      "id": "GV_3",
      "role": "GV",
      "roleName": "Giáo viên (Bộ môn / Chủ nhiệm / Tổ trưởng)",
      "tt": 3,
      "name": "Thiết kế học liệu số, bài giảng điện tử tương tác và ngân hàng câu hỏi trắc nghiệm rèn luyện trực tuyến",
      "spcvFull": "N1_550 - Soạn thảo văn bản hành chính",
      "spcvCode": "N1_550",
      "spcvName": "Soạn thảo văn bản hành chính",
      "deadline": "31/05/2027",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Kho bài giảng điện tử và link học liệu số trên cổng web trường"
    },
    {
      "id": "GV_4",
      "role": "GV",
      "roleName": "Giáo viên (Bộ môn / Chủ nhiệm / Tổ trưởng)",
      "tt": 1,
      "name": "Thực hiện đầy đủ, nghiêm túc số tiết dạy theo phân công thời khóa biểu; lên lớp đúng giờ, không bỏ tiết",
      "spcvFull": "N2_1115 - Kế hoạch triển khai hoạt động chuyên môn",
      "spcvCode": "N2_1115",
      "spcvName": "Kế hoạch triển khai hoạt động chuyên môn",
      "deadline": "31/05/2027",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Sổ đầu bài các lớp, sổ theo dõi chuyên môn của tổ"
    },
    {
      "id": "GV_5",
      "role": "GV",
      "roleName": "Giáo viên (Bộ môn / Chủ nhiệm / Tổ trưởng)",
      "tt": 2,
      "name": "Tích cực đổi mới phương pháp dạy học, phát huy tính tích cực, chủ động, sáng tạo và năng lực tự học của học sinh",
      "spcvFull": "N2_1115 - Kế hoạch triển khai hoạt động chuyên môn",
      "spcvCode": "N2_1115",
      "spcvName": "Kế hoạch triển khai hoạt động chuyên môn",
      "deadline": "31/05/2027",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Phiếu đánh giá tiết dạy đạt loại Khá, Giỏi"
    },
    {
      "id": "GV_6",
      "role": "GV",
      "roleName": "Giáo viên (Bộ môn / Chủ nhiệm / Tổ trưởng)",
      "tt": 3,
      "name": "Tham gia đầy đủ các buổi sinh hoạt chuyên môn của tổ theo định hướng nghiên cứu bài học (tối thiểu 2 lần/tháng)",
      "spcvFull": "N2_1115 - Kế hoạch triển khai hoạt động chuyên môn",
      "spcvCode": "N2_1115",
      "spcvName": "Kế hoạch triển khai hoạt động chuyên môn",
      "deadline": "31/05/2027",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Biên bản sinh hoạt tổ chuyên môn"
    },
    {
      "id": "GV_7",
      "role": "GV",
      "roleName": "Giáo viên (Bộ môn / Chủ nhiệm / Tổ trưởng)",
      "tt": 4,
      "name": "Thực hiện dự giờ đồng nghiệp đúng quy định (đạt 18-20 tiết/năm), trao đổi, rút kinh nghiệm chuyên môn",
      "spcvFull": "N2_1115 - Kế hoạch triển khai hoạt động chuyên môn",
      "spcvCode": "N2_1115",
      "spcvName": "Kế hoạch triển khai hoạt động chuyên môn",
      "deadline": "31/05/2027",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Sổ dự giờ của giáo viên có đầy đủ nhận xét, xếp loại"
    },
    {
      "id": "GV_8",
      "role": "GV",
      "roleName": "Giáo viên (Bộ môn / Chủ nhiệm / Tổ trưởng)",
      "tt": 1,
      "name": "Xây dựng ma trận, bản đặc tả và đề kiểm tra định kỳ (giữa kỳ, cuối kỳ) theo đúng định hướng đánh giá năng lực",
      "spcvFull": "N1_564 - Quản lý dữ liệu của các Kỳ thi",
      "spcvCode": "N1_564",
      "spcvName": "Quản lý dữ liệu của các Kỳ thi",
      "deadline": "31/05/2027",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Hồ sơ ngân hàng đề kiểm tra nộp tổ chuyên môn"
    },
    {
      "id": "GV_9",
      "role": "GV",
      "roleName": "Giáo viên (Bộ môn / Chủ nhiệm / Tổ trưởng)",
      "tt": 2,
      "name": "Chấm bài kiểm tra chính xác, trả bài kịp thời; cập nhật điểm số thường xuyên và định kỳ đầy đủ lên VnEdu",
      "spcvFull": "N1_564 - Quản lý dữ liệu của các Kỳ thi",
      "spcvCode": "N1_564",
      "spcvName": "Quản lý dữ liệu của các Kỳ thi",
      "deadline": "31/05/2027",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Sổ điểm điện tử trên VnEdu đúng tiến độ theo từng mốc thời gian"
    },
    {
      "id": "GV_10",
      "role": "GV",
      "roleName": "Giáo viên (Bộ môn / Chủ nhiệm / Tổ trưởng)",
      "tt": 3,
      "name": "Tham gia công tác coi thi, chấm thi kiểm tra định kỳ, thi thử tốt nghiệp THPT an toàn, nghiêm túc, đúng quy chế",
      "spcvFull": "N1_564 - Quản lý dữ liệu của các Kỳ thi",
      "spcvCode": "N1_564",
      "spcvName": "Quản lý dữ liệu của các Kỳ thi",
      "deadline": "31/05/2027",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Bảng tổng hợp điểm chấm thi và biên bản coi thi"
    },
    {
      "id": "GV_11",
      "role": "GV",
      "roleName": "Giáo viên (Bộ môn / Chủ nhiệm / Tổ trưởng)",
      "tt": 1,
      "name": "Phát hiện, lập danh sách và trực tiếp tham gia bồi dưỡng đội tuyển học sinh giỏi môn phụ trách thi cấp trường, cấp tỉnh",
      "spcvFull": "N2_1108 - Tổ chức kỳ thi chọn Đội tuyển tham dự kỳ thi chọn học sinh giỏi quốc gia THPT năm học 2026 - 2027 (tổ chức ra đề, coi thi, chấm ",
      "spcvCode": "N2_1108",
      "spcvName": "Tổ chức kỳ thi chọn Đội tuyển tham dự kỳ thi chọn học sinh giỏi quốc gia THPT năm học 2026",
      "deadline": "30/03/2027",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Kế hoạch bồi dưỡng HSG và kết quả thi HSG cấp tỉnh"
    },
    {
      "id": "GV_12",
      "role": "GV",
      "roleName": "Giáo viên (Bộ môn / Chủ nhiệm / Tổ trưởng)",
      "tt": 2,
      "name": "Xây dựng kế hoạch và tổ chức dạy phụ đạo, giúp đỡ học sinh học lực yếu kém, có nguy cơ không đạt chuẩn",
      "spcvFull": "N2_1108 - Tổ chức kỳ thi chọn Đội tuyển tham dự kỳ thi chọn học sinh giỏi quốc gia THPT năm học 2026 - 2027 (tổ chức ra đề, coi thi, chấm ",
      "spcvCode": "N2_1108",
      "spcvName": "Tổ chức kỳ thi chọn Đội tuyển tham dự kỳ thi chọn học sinh giỏi quốc gia THPT năm học 2026",
      "deadline": "20/05/2027",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Kế hoạch phụ đạo học sinh yếu kém và theo dõi sự tiến bộ"
    },
    {
      "id": "GV_13",
      "role": "GV",
      "roleName": "Giáo viên (Bộ môn / Chủ nhiệm / Tổ trưởng)",
      "tt": 1,
      "name": "Viết sáng kiến kinh nghiệm hoặc giải pháp đổi mới giáo dục được Hội đồng chuyên môn nhà trường nghiệm thu đạt loại Khá trở lên",
      "spcvFull": "N3_658 - Thẩm định hồ sơ và tham mưu công tác sáng kiến, đề tài nghiên cứu khoa học; các cuộc thi về công tác học sinh sinh viên; hồ sơ b",
      "spcvCode": "N3_658",
      "spcvName": "Thẩm định hồ sơ và tham mưu công tác sáng kiến, đề tài nghiên cứu khoa học; các cuộc thi về công tác học sinh sinh viên; hồ sơ b",
      "deadline": "15/04/2027",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Văn bản báo cáo sáng kiến kinh nghiệm năm học 2026-2027"
    },
    {
      "id": "GV_14",
      "role": "GV",
      "roleName": "Giáo viên (Bộ môn / Chủ nhiệm / Tổ trưởng)",
      "tt": 2,
      "name": "Hướng dẫn học sinh tham gia Cuộc thi Khoa học kỹ thuật (KHKT) cấp trường/cấp tỉnh hoặc các cuộc thi trí tuệ",
      "spcvFull": "N3_658 - Thẩm định hồ sơ và tham mưu công tác sáng kiến, đề tài nghiên cứu khoa học; các cuộc thi về công tác học sinh sinh viên; hồ sơ b",
      "spcvCode": "N3_658",
      "spcvName": "Thẩm định hồ sơ và tham mưu công tác sáng kiến, đề tài nghiên cứu khoa học; các cuộc thi về công tác học sinh sinh viên; hồ sơ b",
      "deadline": "15/01/2027",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Dự án dự thi KHKT học sinh và Quyết định công nhận"
    },
    {
      "id": "GV_15",
      "role": "GV",
      "roleName": "Giáo viên (Bộ môn / Chủ nhiệm / Tổ trưởng)",
      "tt": 1,
      "name": "Xây dựng kế hoạch chủ nhiệm lớp, nắm vững hoàn cảnh từng học sinh; duy trì sĩ số lớp 100%, phòng chống bỏ học",
      "spcvFull": "N1_565 - Quản lý, cập nhật cơ sở dữ liệu học sinh",
      "spcvCode": "N1_565",
      "spcvName": "Quản lý, cập nhật cơ sở dữ liệu học sinh",
      "deadline": "31/05/2027",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Sổ công tác chủ nhiệm lớp, biên bản thăm gia đình học sinh"
    },
    {
      "id": "GV_16",
      "role": "GV",
      "roleName": "Giáo viên (Bộ môn / Chủ nhiệm / Tổ trưởng)",
      "tt": 2,
      "name": "Tổ chức sinh hoạt lớp, giáo dục đạo đức, kỹ năng sống, văn hóa ứng xử học đường và phòng chống bạo lực học đường",
      "spcvFull": "N1_565 - Quản lý, cập nhật cơ sở dữ liệu học sinh",
      "spcvCode": "N1_565",
      "spcvName": "Quản lý, cập nhật cơ sở dữ liệu học sinh",
      "deadline": "31/05/2027",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Giáo án tiết sinh hoạt lớp theo chủ đề hàng tuần"
    },
    {
      "id": "GV_17",
      "role": "GV",
      "roleName": "Giáo viên (Bộ môn / Chủ nhiệm / Tổ trưởng)",
      "tt": 3,
      "name": "Tổ chức các buổi họp phụ huynh học sinh đầu năm, giữa kỳ, cuối năm; giữ mối liên lạc chặt chẽ với cha mẹ học sinh qua Zalo/Smas",
      "spcvFull": "N1_565 - Quản lý, cập nhật cơ sở dữ liệu học sinh",
      "spcvCode": "N1_565",
      "spcvName": "Quản lý, cập nhật cơ sở dữ liệu học sinh",
      "deadline": "31/05/2027",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Biên bản họp Ban đại diện cha mẹ học sinh lớp"
    },
    {
      "id": "GV_18",
      "role": "GV",
      "roleName": "Giáo viên (Bộ môn / Chủ nhiệm / Tổ trưởng)",
      "tt": 4,
      "name": "Đánh giá, nhận xét rèn luyện và học tập của học sinh; cập nhật kết quả hạnh kiểm, khen thưởng đầy đủ lên phần mềm CSDL",
      "spcvFull": "N1_565 - Quản lý, cập nhật cơ sở dữ liệu học sinh",
      "spcvCode": "N1_565",
      "spcvName": "Quản lý, cập nhật cơ sở dữ liệu học sinh",
      "deadline": "31/05/2027",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Hồ sơ đánh giá rèn luyện học kỳ 1, học kỳ 2 trên VnEdu"
    },
    {
      "id": "GV_19",
      "role": "GV",
      "roleName": "Giáo viên (Bộ môn / Chủ nhiệm / Tổ trưởng)",
      "tt": 1,
      "name": "Tham gia đầy đủ các lớp bồi dưỡng thường xuyên, bồi dưỡng chuyên môn nghiệp vụ theo quy định của Sở GD&ĐT",
      "spcvFull": "N3_652 - Xây dựng Kế hoạch đào tạo, bồi dưỡng công chức, viên chức",
      "spcvCode": "N3_652",
      "spcvName": "Xây dựng Kế hoạch đào tạo, bồi dưỡng công chức, viên chức",
      "deadline": "31/05/2027",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Giấy chứng nhận bồi dưỡng thường xuyên hoặc kết quả trên cổng bồi dưỡng"
    },
    {
      "id": "GV_20",
      "role": "GV",
      "roleName": "Giáo viên (Bộ môn / Chủ nhiệm / Tổ trưởng)",
      "tt": 2,
      "name": "Tự bồi dưỡng nâng cao trình độ chuyên môn, năng lực ứng dụng CNTT, ngoại ngữ và kỹ năng sư phạm hiện đại",
      "spcvFull": "N3_652 - Xây dựng Kế hoạch đào tạo, bồi dưỡng công chức, viên chức",
      "spcvCode": "N3_652",
      "spcvName": "Xây dựng Kế hoạch đào tạo, bồi dưỡng công chức, viên chức",
      "deadline": "31/05/2027",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Kế hoạch tự học và bài thu hoạch bồi dưỡng thường xuyên cá nhân"
    }
  ],
  "nv": [
    {
      "id": "NV_1",
      "role": "NV",
      "roleName": "Nhân viên (Kế toán / Văn thư / Thiết bị / Y tế / CNTT)",
      "tt": 1,
      "name": "Tiếp nhận, kiểm tra tính hợp pháp, hợp lệ của chứng từ thu chi, đề nghị thanh toán theo Quy chế chi tiêu nội bộ",
      "spcvFull": "N1_594 - Thu thập và xử lý thông tin số liệu chứng từ kế toán",
      "spcvCode": "N1_594",
      "spcvName": "Thu thập và xử lý thông tin số liệu chứng từ kế toán",
      "deadline": "31/05/2027",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Bộ chứng từ thanh toán thu - chi lưu tại phòng Tài chính - Kế toán"
    },
    {
      "id": "NV_2",
      "role": "NV",
      "roleName": "Nhân viên (Kế toán / Văn thư / Thiết bị / Y tế / CNTT)",
      "tt": 2,
      "name": "Lập phiếu thu, phiếu chi, giấy đề nghị rút hạn mức, ủy nhiệm chi và cập nhật số liệu chính xác vào phần mềm MISA",
      "spcvFull": "N1_594 - Thu thập và xử lý thông tin số liệu chứng từ kế toán",
      "spcvCode": "N1_594",
      "spcvName": "Thu thập và xử lý thông tin số liệu chứng từ kế toán",
      "deadline": "31/05/2027",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Dữ liệu kế toán xuất từ phần mềm MISA"
    },
    {
      "id": "NV_3",
      "role": "NV",
      "roleName": "Nhân viên (Kế toán / Văn thư / Thiết bị / Y tế / CNTT)",
      "tt": 1,
      "name": "Lập hồ sơ rút dự toán thanh toán tiền lương, các khoản phụ cấp, chế độ bảo hiểm xã hội, BHYT, KPCĐ đúng hạn hàng tháng",
      "spcvFull": "N1_599 - Thực hiện giao dịch kho bạc , ngân hàng",
      "spcvCode": "N1_599",
      "spcvName": "Thực hiện giao dịch kho bạc , ngân hàng",
      "deadline": "31/05/2027",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Bảng thanh toán tiền lương có chữ ký và xác nhận của KBNN"
    },
    {
      "id": "NV_4",
      "role": "NV",
      "roleName": "Nhân viên (Kế toán / Văn thư / Thiết bị / Y tế / CNTT)",
      "tt": 2,
      "name": "Đối chiếu số liệu tài khoản tiền gửi, tiền dự toán ngân sách định kỳ hàng tháng, quý với Kho bạc Nhà nước",
      "spcvFull": "N1_599 - Thực hiện giao dịch kho bạc , ngân hàng",
      "spcvCode": "N1_599",
      "spcvName": "Thực hiện giao dịch kho bạc , ngân hàng",
      "deadline": "31/05/2027",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Biên bản xác nhận số dư tài khoản tại Kho bạc Nhà nước"
    },
    {
      "id": "NV_5",
      "role": "NV",
      "roleName": "Nhân viên (Kế toán / Văn thư / Thiết bị / Y tế / CNTT)",
      "tt": 1,
      "name": "Lập báo cáo quyết toán tài chính ngân sách năm học và quyết toán ngân sách nhà nước năm đúng hạn",
      "spcvFull": "N3_695 - Tổng hợp và lập báo cáo tài chính hợp nhất, báo cáo quyết toán năm",
      "spcvCode": "N3_695",
      "spcvName": "Tổng hợp và lập báo cáo tài chính hợp nhất, báo cáo quyết toán năm",
      "deadline": "31/01/2027",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Báo cáo tài chính năm 2026 gửi Sở GD&ĐT và Kho bạc"
    },
    {
      "id": "NV_6",
      "role": "NV",
      "roleName": "Nhân viên (Kế toán / Văn thư / Thiết bị / Y tế / CNTT)",
      "tt": 2,
      "name": "Thực hiện công khai tài chính quý, năm và phục vụ chu đáo các đợt thanh tra, kiểm tra, kiểm toán tài chính",
      "spcvFull": "N3_695 - Tổng hợp và lập báo cáo tài chính hợp nhất, báo cáo quyết toán năm",
      "spcvCode": "N3_695",
      "spcvName": "Tổng hợp và lập báo cáo tài chính hợp nhất, báo cáo quyết toán năm",
      "deadline": "31/05/2027",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Biểu mẫu công khai tài chính niêm yết tại bảng tin cơ quan"
    },
    {
      "id": "NV_7",
      "role": "NV",
      "roleName": "Nhân viên (Kế toán / Văn thư / Thiết bị / Y tế / CNTT)",
      "tt": 1,
      "name": "Tiếp nhận, đăng ký, chuyển giao kịp thời văn bản đến trên hệ thống quản lý văn bản iOffice/VNPT iOffice",
      "spcvFull": "N1_602 - Quản lý và xử lý văn bản đi, đến (Chính quyền + Đảng ủy)",
      "spcvCode": "N1_602",
      "spcvName": "Quản lý và xử lý văn bản đi, đến (Chính quyền + Đảng ủy)",
      "deadline": "31/05/2027",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Sổ theo dõi văn bản đến và dữ liệu trên phần mềm quản lý văn bản"
    },
    {
      "id": "NV_8",
      "role": "NV",
      "roleName": "Nhân viên (Kế toán / Văn thư / Thiết bị / Y tế / CNTT)",
      "tt": 2,
      "name": "Kiểm tra thể thức, lấy số, phát hành văn bản đi của nhà trường đảm bảo đúng quy chuẩn kỹ thuật văn bản",
      "spcvFull": "N1_602 - Quản lý và xử lý văn bản đi, đến (Chính quyền + Đảng ủy)",
      "spcvCode": "N1_602",
      "spcvName": "Quản lý và xử lý văn bản đi, đến (Chính quyền + Đảng ủy)",
      "deadline": "31/05/2027",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Sổ văn bản đi năm học 2026-2027"
    },
    {
      "id": "NV_9",
      "role": "NV",
      "roleName": "Nhân viên (Kế toán / Văn thư / Thiết bị / Y tế / CNTT)",
      "tt": 1,
      "name": "Quản lý và sử dụng con dấu, USB token chữ ký số cơ quan an toàn, chặt chẽ, đúng thẩm quyền",
      "spcvFull": "N1_603 - Quản lý và sử dụng con dấu, thiết bị lưu khóa bí mật; thực hiện ký số chuyển thủ tục hành chính trên dịch vụ công",
      "spcvCode": "N1_603",
      "spcvName": "Quản lý và sử dụng con dấu, thiết bị lưu khóa bí mật; thực hiện ký số chuyển thủ tục hành chính trên dịch vụ công",
      "deadline": "31/05/2027",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Sổ theo dõi đóng dấu và nhật ký ký số điện tử"
    },
    {
      "id": "NV_10",
      "role": "NV",
      "roleName": "Nhân viên (Kế toán / Văn thư / Thiết bị / Y tế / CNTT)",
      "tt": 2,
      "name": "Thực hiện tiếp nhận và giải quyết thủ tục hành chính: cấp bản sao học bạ, giấy chứng nhận tốt nghiệp cho học sinh đúng hạn",
      "spcvFull": "N1_603 - Quản lý và sử dụng con dấu, thiết bị lưu khóa bí mật; thực hiện ký số chuyển thủ tục hành chính trên dịch vụ công",
      "spcvCode": "N1_603",
      "spcvName": "Quản lý và sử dụng con dấu, thiết bị lưu khóa bí mật; thực hiện ký số chuyển thủ tục hành chính trên dịch vụ công",
      "deadline": "31/05/2027",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Sổ cấp phát văn bằng chứng chỉ, giấy chứng nhận"
    },
    {
      "id": "NV_11",
      "role": "NV",
      "roleName": "Nhân viên (Kế toán / Văn thư / Thiết bị / Y tế / CNTT)",
      "tt": 1,
      "name": "Thu thập, phân loại, chỉnh lý hồ sơ thi đua, bài thi tốt nghiệp, sổ điểm của các năm học đưa vào kho lưu trữ",
      "spcvFull": "N1_604 - Thu thập hồ sơ tài liệu vào kho lưu trữ, phục vụ khai thác, sử dụng tài liệu lưu trữ",
      "spcvCode": "N1_604",
      "spcvName": "Thu thập hồ sơ tài liệu vào kho lưu trữ, phục vụ khai thác, sử dụng tài liệu lưu trữ",
      "deadline": "31/05/2027",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Danh mục hồ sơ tài liệu nộp lưu trữ cơ quan năm học"
    },
    {
      "id": "NV_12",
      "role": "NV",
      "roleName": "Nhân viên (Kế toán / Văn thư / Thiết bị / Y tế / CNTT)",
      "tt": 2,
      "name": "Bảo quản an toàn kho tài liệu lưu trữ, chống ẩm, mối mọt; phục vụ tra cứu hồ sơ nhanh chóng, chính xác",
      "spcvFull": "N1_604 - Thu thập hồ sơ tài liệu vào kho lưu trữ, phục vụ khai thác, sử dụng tài liệu lưu trữ",
      "spcvCode": "N1_604",
      "spcvName": "Thu thập hồ sơ tài liệu vào kho lưu trữ, phục vụ khai thác, sử dụng tài liệu lưu trữ",
      "deadline": "31/05/2027",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Nhật ký khai thác, sử dụng tài liệu lưu trữ"
    },
    {
      "id": "NV_13",
      "role": "NV",
      "roleName": "Nhân viên (Kế toán / Văn thư / Thiết bị / Y tế / CNTT)",
      "tt": 1,
      "name": "Quản lý quỹ tiền mặt tuyệt đối an toàn; thực hiện thu - chi tiền mặt chính xác, kịp thời theo lệnh thu - chi hợp lệ",
      "spcvFull": "N1_605 - Quản lý thu, chi tiền mặt tại quỹ, Kiêm nhiệm Thủ quỹ cơ quan; thực hiện các giao dịch tại Kho bạc/Ngân hàng",
      "spcvCode": "N1_605",
      "spcvName": "Quản lý thu, chi tiền mặt tại quỹ, Kiêm nhiệm Thủ quỹ cơ quan; thực hiện các giao dịch tại Kho bạc/Ngân hàng",
      "deadline": "31/05/2027",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Sổ quỹ tiền mặt có đối chiếu hàng ngày giữa Thủ quỹ và Kế toán"
    },
    {
      "id": "NV_14",
      "role": "NV",
      "roleName": "Nhân viên (Kế toán / Văn thư / Thiết bị / Y tế / CNTT)",
      "tt": 2,
      "name": "Chi trả kịp thời tiền học bổng, tiền hỗ trợ chi phí học tập cho học sinh diện chính sách, vùng cao đầy đủ chữ ký",
      "spcvFull": "N1_605 - Quản lý thu, chi tiền mặt tại quỹ, Kiêm nhiệm Thủ quỹ cơ quan; thực hiện các giao dịch tại Kho bạc/Ngân hàng",
      "spcvCode": "N1_605",
      "spcvName": "Quản lý thu, chi tiền mặt tại quỹ, Kiêm nhiệm Thủ quỹ cơ quan; thực hiện các giao dịch tại Kho bạc/Ngân hàng",
      "deadline": "31/05/2027",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Danh sách học sinh nhận tiền chính sách có chữ ký người nhận"
    },
    {
      "id": "NV_15",
      "role": "NV",
      "roleName": "Nhân viên (Kế toán / Văn thư / Thiết bị / Y tế / CNTT)",
      "tt": 1,
      "name": "Lập kế hoạch quản lý, bảo dưỡng và chuẩn bị thiết bị, hóa chất phục vụ các tiết dạy thực hành môn Lý, Hóa, Sinh",
      "spcvFull": "N4_182 - Tham mưu Quyết đinh quy định định tiêu chuẩn, định mức về máy móc thiết bị dạy học",
      "spcvCode": "N4_182",
      "spcvName": "Tham mưu Quyết đinh quy định định tiêu chuẩn, định mức về máy móc thiết bị dạy học",
      "deadline": "31/05/2027",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Sổ mượn trả thiết bị và nhật ký sử dụng phòng thí nghiệm"
    },
    {
      "id": "NV_16",
      "role": "NV",
      "roleName": "Nhân viên (Kế toán / Văn thư / Thiết bị / Y tế / CNTT)",
      "tt": 2,
      "name": "Thực hiện kiểm kê tài sản thiết bị định kỳ; đề xuất mua sắm bổ sung thiết bị dạy học tối thiểu và thanh lý đồ hỏng",
      "spcvFull": "N4_182 - Tham mưu Quyết đinh quy định định tiêu chuẩn, định mức về máy móc thiết bị dạy học",
      "spcvCode": "N4_182",
      "spcvName": "Tham mưu Quyết đinh quy định định tiêu chuẩn, định mức về máy móc thiết bị dạy học",
      "deadline": "31/05/2027",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Biên bản kiểm kê thiết bị dạy học cuối kỳ/năm"
    },
    {
      "id": "NV_17",
      "role": "NV",
      "roleName": "Nhân viên (Kế toán / Văn thư / Thiết bị / Y tế / CNTT)",
      "tt": 1,
      "name": "Quản lý kho sách, cấp phát SGK, SGV và tài liệu tham khảo cho giáo viên, học sinh ngay đầu năm học mới",
      "spcvFull": "N2_1067 - Báo cáo kết quả tổ chức thực hiện ngày Sách và Văn hóa đọc Việt Nam năm 2026",
      "spcvCode": "N2_1067",
      "spcvName": "Báo cáo kết quả tổ chức thực hiện ngày Sách và Văn hóa đọc Việt Nam năm 2026",
      "deadline": "30/09/2026",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Sổ đăng ký cá biệt, sổ mượn trả sách thư viện"
    },
    {
      "id": "NV_18",
      "role": "NV",
      "roleName": "Nhân viên (Kế toán / Văn thư / Thiết bị / Y tế / CNTT)",
      "tt": 2,
      "name": "Tổ chức hoạt động hưởng ứng Ngày Sách và Văn hóa đọc Việt Nam, tuyên truyền giới thiệu sách hay cho học sinh",
      "spcvFull": "N2_1067 - Báo cáo kết quả tổ chức thực hiện ngày Sách và Văn hóa đọc Việt Nam năm 2026",
      "spcvCode": "N2_1067",
      "spcvName": "Báo cáo kết quả tổ chức thực hiện ngày Sách và Văn hóa đọc Việt Nam năm 2026",
      "deadline": "30/04/2027",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Kế hoạch và báo cáo tổ chức Ngày hội đọc sách năm học"
    },
    {
      "id": "NV_19",
      "role": "NV",
      "roleName": "Nhân viên (Kế toán / Văn thư / Thiết bị / Y tế / CNTT)",
      "tt": 1,
      "name": "Quản lý tủ thuốc y tế trường học; lập kế hoạch và tổ chức sơ cứu, chăm sóc sức khỏe ban đầu cho học sinh và cán bộ",
      "spcvFull": "N2_1066 - Báo cáo công tác xây dựng giáo dục môi trường an toàn lành mạnh và phòng chống bạo lực học đường",
      "spcvCode": "N2_1066",
      "spcvName": "Báo cáo công tác xây dựng giáo dục môi trường an toàn lành mạnh và phòng chống bạo lực học đường",
      "deadline": "31/05/2027",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Sổ theo dõi khám chữa bệnh và cấp phát thuốc sơ cứu"
    },
    {
      "id": "NV_20",
      "role": "NV",
      "roleName": "Nhân viên (Kế toán / Văn thư / Thiết bị / Y tế / CNTT)",
      "tt": 2,
      "name": "Tuyên truyền phòng chống dịch bệnh theo mùa, vệ sinh an toàn thực phẩm, vận động học sinh tham gia BHYT đạt 100%",
      "spcvFull": "N2_1066 - Báo cáo công tác xây dựng giáo dục môi trường an toàn lành mạnh và phòng chống bạo lực học đường",
      "spcvCode": "N2_1066",
      "spcvName": "Báo cáo công tác xây dựng giáo dục môi trường an toàn lành mạnh và phòng chống bạo lực học đường",
      "deadline": "31/05/2027",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Báo cáo y tế học đường và tỷ lệ học sinh tham gia BHYT đạt 100%"
    },
    {
      "id": "NV_21",
      "role": "NV",
      "roleName": "Nhân viên (Kế toán / Văn thư / Thiết bị / Y tế / CNTT)",
      "tt": 1,
      "name": "Quản trị, vận hành hệ thống mạng internet, phòng máy tính tin học, bảo đảm kết nối thông suốt phục vụ học tập và thi",
      "spcvFull": "N2_1085 - Triển khai cảnh báo các lỗ hổng bảo mật, an toàn thông tin theo hướng dẫn của cơ quan chuyên môn",
      "spcvCode": "N2_1085",
      "spcvName": "Triển khai cảnh báo các lỗ hổng bảo mật, an toàn thông tin theo hướng dẫn của cơ quan chuyên môn",
      "deadline": "31/05/2027",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Nhật ký vận hành phòng máy tính và bảo dưỡng định kỳ hệ thống mạng"
    },
    {
      "id": "NV_22",
      "role": "NV",
      "roleName": "Nhân viên (Kế toán / Văn thư / Thiết bị / Y tế / CNTT)",
      "tt": 2,
      "name": "Quản trị kỹ thuật cổng thông tin điện tử (website) nhà trường, hỗ trợ kỹ thuật phần mềm CSDL, học bạ số và chữ ký số",
      "spcvFull": "N2_1085 - Triển khai cảnh báo các lỗ hổng bảo mật, an toàn thông tin theo hướng dẫn của cơ quan chuyên môn",
      "spcvCode": "N2_1085",
      "spcvName": "Triển khai cảnh báo các lỗ hổng bảo mật, an toàn thông tin theo hướng dẫn của cơ quan chuyên môn",
      "deadline": "31/05/2027",
      "targetQuantity": 100,
      "targetQuality": 100,
      "targetProgress": 100,
      "notes": "Báo cáo an toàn thông tin và dữ liệu sao lưu định kỳ hệ thống"
    }
  ]
};

export const ALL_JOBS: JobItem[] = [
  ...JOBS_DATA.cbql,
  ...JOBS_DATA.gv,
  ...JOBS_DATA.nv
];
